### ISSUE TITLE
XEMM: rate oracle confirmation not shown during start of the strategy

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#5287] opened 2022-05-04 12:33 UTC
**Describe the bug**
After creating a new cross exchange strategy, once started, it is expected to show the current rate conversion if `use_oracle_conversion_rate` is set to `true`. However, the client doesn't seem to display the rate, although the strategy still works as expected. Issues randomly happen.

Current behavior:
![image](https://user-images.githubusercontent.com/57189990/166681165-11299534-535c-4dcb-8124-bc9586a61141.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/57189990/166680733-8caab633-f124-4732-b8be-7b4cbbe77cc4.png)

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a cross-exchange market making strategy using Binance as maker exchange and Crypto_com as taker (can use other exchanges)
2. Enable use_oracle_conversion_rate
3. Start the strategy
4. Verify if the rate conversation is shown
...

**Screenshots**

**Release version**
master and dev (1.3.0)

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by nikspz** [comment] 2022-09-28 19:09
Reproduced on dev-1.8.0
Bot not showing rate oracle for the same pairs on taker and maker exchanges

Also we have this issue using different pairs https://github.com/hummingbot/hummingbot/issues/5068

**Comment by rapcmia** [comment] 2022-09-30 06:05
Closing ticket, XEMM has been redesigned since the deployment of Pydantic to Hummingbot client. A new approach using `conversion_rate_mode` has been added to improve UX

**Closed by rapcmia** 2022-09-30 06:05 UTC
Labels: P3, bug, cross_exchange_market_making
