### ISSUE TITLE
Liquidity Mining - KuCoin Connected

### ISSUE THREAD

**Issue by se-taylor** [hummingbot/hummingbot#5560] opened 2022-08-02 22:42 UTC
I am looking for confirmation that this is setup and running correctly? Everything "appears" to be working. I am seeing earnings and data on the dashboard and the miner is connected to KuCoin.

My setup is MacOS, using the Docker image install. Release version = v1.6.0

Here are some items you will see in the screenshots below:
- Terminal shows 0 for trades, p&l, return
- Nothing displays when typing 'history'. KuCoin is showing trades.
- When I start the bot, it shows a Connector Status: YELLOW but no description.
- I also see a "parrot - Unexpected error .... from Hummingbot API" while it runs.

**Question**
Did I miss a step or misconfigure something?

**Screens**
<img width="1388" alt="Connector Status Yellow and Parrot Error" src="https://user-images.githubusercontent.com/102394171/182485287-e2a29158-8e93-459b-a57f-d3385a817312.png">
<img width="1134" alt="Hummingbot Miner Data" src="https://user-images.githubusercontent.com/102394171/182485295-cc2d0f9e-2c4e-4cf2-8dfd-380b952a3a4d.png">
<img width="874" alt="KuCoin Order History" src="https://user-images.githubusercontent.com/102394171/182485296-b5e012f6-d4cb-4a26-a83f-166fd2120563.png">
<img width="875" alt="KuCoin Trade History" src="https://user-images.githubusercontent.com/102394171/182485297-db10d5c4-4c8d-475e-86db-d35fd57f04e9.png">
<img width="1381" alt="No past trades to report" src="https://user-images.githubusercontent.com/102394171/182485298-e8d36548-84e3-4506-85cf-1606b2034562.png">

**Logs**
[logs_conf_liquidity_mining_1.log](https://github.com/hummingbot/hummingbot/files/9246076/logs_conf_liquidity_mining_1.log)

**Comment by nikspz** [comment] 2022-08-03 03:54
Regarding (`parrot - ERROR - Unexpected error while requesting data from Hummingbot API.` ) issue reported is duplicated , that's a known issue when checking status using LM strategy (Liquidity Mining - Unexpected error while requesting data from Hummingbot API #5240), you could add your comment there.
![liquidity mining status](https://user-images.githubusercontent.com/83953535/182520670-f169a6bc-742b-4556-9251-28b0197a6af8.gif)

**Comment by nikspz** [comment] 2022-08-03 03:57
Regarding `Connector Status: YELLOW` it means that connector has isssues reported earlier
you could check it here:
https://github.com/hummingbot/hummingbot/issues?q=is%3Aissue+is%3Aopen+kucoin

**Comment by nikspz** [comment] 2022-08-03 04:27
regarding history, upon checking, could't replicate your issue.

Terminal shows trades, p&l, return
Bot display history and `history --verbose`, showing trades for KuCoin
![history kucoin LM](https://user-images.githubusercontent.com/83953535/182523533-5ed8e84d-6dd3-47fc-93a9-b5d0c6bc0f8d.gif)
![image](https://user-images.githubusercontent.com/83953535/182523789-1bc9b8f6-1c88-49f0-acc4-51d9ed0c577e.png)
![image](https://user-images.githubusercontent.com/83953535/182524054-70d902c2-0b18-407a-9e1f-d44d7d56d44b.png)

If you want to see history after bot restarted try history --verbose --days 7 (amount of days)
https://hummingbot.org/operation/history/

**Comment by se-taylor** [comment] 2022-08-03 13:33
> --days 7

I tried restart and then history --verbose --days 7, still no history displayed. As long as it is working, I am ok with checking it on KuCoin, but is my setup working?

**Comment by nikspz** [comment] 2022-08-03 13:46
Yes, upon checking logs file that you provided, there's no filled trades there in the logs. So bot not showing trades, because current strategy you ran didn't have trades. Upon checking ver 1.6.0 okay with history using Kucoin

**Comment by se-taylor** [comment] 2022-08-03 14:17
> Yes, upon checking logs file that you provided, there's no filled trades there in the logs. So bot not showing trades, because strategy you ran didn't have trades. Upon checking ver 1.6.0 okay with history using Kucoin

Ok, I will update the strategy, thank you for your help!

**Comment by nikspz** [comment] 2022-08-03 16:14
That's expected behavior for your config. if you want to get filled trades you could set up more tight spread.

**Comment by se-taylor** [comment] 2022-08-03 16:15
> That's expected behavior for your config. if you want to get filled trades you could set up more tight spread.

Ok, this is where I was headed, thx again! I am diving into your docs to learn more of the advanced settings :)

**Comment by nikspz** [comment] 2022-08-03 16:19
You could join our discord's #trader-chat if you want to discuss with other traders or #support/ #general channel to get help from our community manager.

**Comment by JeremyKono** [comment] 2022-08-04 02:12
Closing the issue as it is proved to be not a bug by QA.

**Closed by JeremyKono** 2022-08-04 02:12 UTC
Labels: bug, kucoin
