### ISSUE TITLE
Bybit perpetual - Failed to start PerpetualMM strategy

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5827] opened 2022-10-24 22:08 UTC
Bybit Perpetual failed to start Perpetual market making strategy. Showed `ERROR - Unhandled error in background task: [<class 'decimal.ConversionSyntax'>]` on the start of the bot

**Steps To Reproduce**
1. Create perpetualMM strategy using bybit perpetual as the exchange
2. Start the strategy

Actual behavior:
Bot showed WARNING - Changing position mode to ONEWAY did not succeed.
Then stuck into `Markets are not ready. No market making trades are permitted.`

Expected behavior:
Connected to exchange and initializing the order book successfully
No error should occur.
Orders to open position gets created

**Release version**
development 1.9.0 master 1.8.0

[logs_conf_perpetual_market_making_1.log](https://github.com/hummingbot/hummingbot/files/9855661/logs_conf_perpetual_market_making_1.log)
[bybitperp.zip](https://github.com/hummingbot/hummingbot/files/9855665/bybitperp.zip)

```
2022-10-24 21:03:50,316 - 258466 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-10-24 21:03:50,373 - 258466 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Changing position mode to ONEWAY succeeded.
2022-10-24 21:03:50,864 - 258466 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative.BybitPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-10-24 21:03:51,127 - 258466 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for ETH-USDT. 1/1 completed.
2022-10-24 21:03:51,179 - 258466 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/home/ubuntu/staging/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/staging/hummingbot/connector/perpetual_derivative_py_base.py", line 318, in _listen_for_funding_info
    await self._init_funding_info()
  File "/home/ubuntu/staging/hummingbot/connector/perpetual_derivative_py_base.py", line 325, in _init_funding_info
    funding_info = await self._orderbook_ds.get_funding_info(trading_pair)
  File "/home/ubuntu/staging/hummingbot/connector/derivative/bybit_perpetual/bybit_perpetual_api_order_book_data_source.py", line 51, in get_funding_info
    rate=Decimal(str(symbol_info["predicted_funding_rate"])),
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
2022-10-24 21:03:51,180 - 258466 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - Changing position mode to ONEWAY did not succeed.
2022-10-24 21:03:51,181 - 258466 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative.BybitPerpetualDerivative - INFO - Leverage for ETH-USDT successfully set to 1.
2022-10-24 21:03:51,587 - 258466 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_api_order_book_data_source.BybitPerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
2022-10-24 21:03:51,811 - 258466 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_user_stream_data_source.BybitPerpetualUserStreamDataSource - INFO - Subscribed to private account and orders channels wss://stream.bybit.com/realtime...
2022-10-24 21:03:51,869 - 258466 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_user_stream_data_source.BybitPerpetualUserStreamDataSource - INFO - Subscribed to private account and orders channels wss://stream.bybit.com/realtime_private...
2022-10-24 21:04:01,173 - 258466 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Changing position mode to ONEWAY succeeded.
2022-10-24 21:15:00,000 - 258466 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - Markets are not ready. No market making trades are permitted.
2022-10-24 21:30:00,001 - 258466 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - Markets are not ready. No market making trades are permitted.
2022-10-24 21:45:00,001 - 258466 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - Markets are not ready. No market making trades are permitted.
2022-10-24 22:00:00,002 - 258466 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - Markets are not ready. No market making trades are permitted.
```
![image](https://user-images.githubusercontent.com/83953535/197638866-22228a22-f499-4c5f-bcb3-254c5a80ccdf.png)

**Comment by MementoRC** [comment] 2022-10-25 14:21
@nikspz @rapcmia This is a duplicate of: https://github.com/hummingbot/hummingbot/issues/5824

**Comment by nikspz** [comment] 2022-10-26 11:37
Fixed with https://github.com/hummingbot/hummingbot/pull/5829 / #5830

**Closed** 2022-10-27 04:02 UTC
Labels: P2, bug, bybit_perpetual, perpetual_market_making, staging
