### ISSUE TITLE
Binance perpetual: Stuck cancelling an order

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#5076] opened 2022-01-31 03:45 UTC
**Describe the bug**
Opening ticket for tracking:
When running a perpetual market making strategy using binance perpetual for long period (days), there are instances that the bot gets stuck in a repeated loop, attempting to cancel an order. When you check the exchange, there are no active closing position. In this screenshot, both orders `x-3QreWesy-SDEUT75601643346706004336` and `x-3QreWesy-BDEUT75601643346706004126` fails to cancel. In the logs, these affected orders didn't receive any completion event for the cancellation.
<img width="1620" alt="binance_perp-stuck-cancelling" src="https://user-images.githubusercontent.com/57189990/151735532-6977f828-513a-4872-930c-5506ea604894.png">

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a perpetual market making strategy using binance_perpetual as connector
2. Start the the strategy and leave the bot running for long period or few days.
3. Regularly monitor the bot for any cancellation issue

**Screenshots**

**Release version**
0.46.0

**Attachments**

[binance-perp-cancel-issue.zip](https://github.com/hummingbot/hummingbot/files/7967914/binance-perp-cancel-issue.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by leastchaos** [comment] 2022-02-01 02:32
This is also happening with XEMM.
Attached is my logs for XEMM, but it is slightly modified which should not impact this part.
[logs_conf_xemm_gt.log.txt](https://github.com/hummingbot/hummingbot/files/7975481/logs_conf_xemm_gt.log.txt)
.

**Comment by leastchaos** [comment] 2022-02-02 01:55
This is also happening on my custom strategy which was previously working fine on v0.46.0. I have to revert all my bots including default XEMM back to 0.46.0 as v1.0.0 is unusable because of this bug. It seems that the bot is unable to recover from missing order cancellation event.

**Comment by BGTCapital** [comment] 2022-06-16 19:06
We have noticed this error on Binance Perpetuals, that turn the strategy completely useless. Does any one have any idea on how to fix this, or if we can use a different exchange?

**Comment by Cianurosodico** [comment] 2022-07-01 14:42
Still having same issue, some one working on a fix?

**Comment by nikspz** [comment] 2022-08-29 09:42
Replicated using staging-1.7.0

**Comment by rapcmia** [comment] 2022-09-02 02:06
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to certified exchange

**Comment by raymondcarl** [comment] 2022-09-02 19:37
I checked a few things:
1) On the websocket protocol level, the Ping / Pong frames between the WSConnection class and the binance websocker server are working even after the BinancePerpetualDerivative class gets stuck in the cancellation loop. So, it seems like the connection is still present.

2) The call to the binance server to cancel the order works fine. The order actually shows as cancelled on the binance side. However, the message is either 1) never sent over the websocket confirming the order cancellation, or 2) the message is sent but is not registering on the hummingbot side. I setup logging to check all messages coming over the socket, and when this issue happens, the message showing a cancellation of the order never shows in the log. This causes _execute_cancel to fail because the client order tracker does not show the respective order in the tracked_order boolean variable. Hence, _execute_cancel (binance perpetual class) simply returns without a return value. This to binance perpetual being stuck in a loop where it tries to cancel the order, but it does not show as a tracked order. From what I remember, self._client_order_tracker.fetch_order is a call to the API (not the WS), and this is not returning a valid order since it is already cancelled. 

Another idea I had is that it could be some kind of timeout on the Binance side, but I assume that the WS would actually be disconnected in this case.

**Comment by han-qiu** [comment] 2022-09-05 18:17
Is this one already assigned to you? @cardosofede

**Comment by raymondcarl** [comment] 2022-09-08 19:22
I think the error is caused in _execute_cancel in /connector/derivative/binance_perpetual/binance_perpetual_derivative.py. If you compare it with the way the bitmex handles cases where the exchange does not recognize the order id, I think handling those cases in the same way and separating it from check for tracked_order.is_pending_create might fix this.

**Comment by cardosofede** [comment] 2022-09-08 22:04
@raymondcarl hey Raymond! thanks for the previous investigation, tomorrow I will fix this issue (hope so haha). Some things about your comments.
- The ws is not necessary here because the cancel is via rest
- If we are missing one of the messages (i.e. canceled order message) the client should have some logic to handle this via rest.
- The method fetch order is using the dictionaries stored in the client order tracker: in_flight_orders + cached_orders
- The execute cancel has a logic to stop tracking the order if the response is that the order don't exist
<img width="771" alt="image" src="https://user-images.githubusercontent.com/36869960/189233759-ee714946-d185-4b19-b1ba-2a4b201cf8b2.png">

My guess is that as we are using the cached orders + inflight orders to cancel the order, it will try to cancel the same order at least for 30 seconds (the default value for the TTL cache).

Tomorrow I will debug it because this are all thoughts!

**Comment by raymondcarl** [comment] 2022-09-09 18:47
Hi @cardosofede : I deleted my previous message because I thought I found the issue, but still happened. I still think that there may be an issue with how  _execute_cancel in (hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py) handles the cases where the call to fetch order returns none by looking at the bitmex implementation of the same function (cancel_order).  I think it should work better to check if the result is None first, and then check if tracked_order.is_pending_create. I can't remember for sure, but I believe that if tracked_order is None, the conditional check for tracked_order.is_pending_create should throw an error since you shouldn't have a property for object type None. Not sure if you need to do a safe check in Python or not, but the Bitmex derivative connector seemed to handle it in a good way.

I made an adjustment for the above, and now it seems like everything is working OK up until stop_tracking_order is called. In stop tracking order, I see that the it is working correctly, but even though self._client_order_tracker.active_orders does not show the order, the order is still active somewhere.

I think my confusion is what is the link between hummingbot.connector.client_order_tracker and what the strategy actually uses for the order tracker in /hummingbot/strategy/order_tracker.pyx. It seems like the connector and the strategy have 2 different copies of the active orders. I'm trying to find the class that links the two, and I believe it might be OrderBook.

Given that this only applies to Binance derivatives, my 2 theories on what's happening are:
1) async problem with binance derivative connector order updating, or
2) a breakdown in the copy of the orderbook used by the strategies that is specific to binance.

#2 above is strange to me because it seems that the the stop_tracking_order function is working and the order is not showing self._client_order_tracker.active_orders.

I don't see anywhere where #1 could be happening, but it makes more sense because the issue is not continuous. From my perspective, it happens randomly. It can happen after 2 minutes or after 4 hours. I don't see anything specific that triggers it.

Also, on what you mention about the cached orders, it will stay stuck in the loop for longer than 30 seconds. From my experience, it happens indefinitely when it occurs.

Good luck tomorrow because it seems like a really tough problem.

**Comment by pulkitsharma** [comment] 2022-09-12 17:08
The pull request #5683  does not solve the problem.

**Comment by cardosofede** [comment] 2022-09-12 18:54
hey guys!! thank you very much for the testing... @pulkitsharma @raymondcarl 
that's very strange, because if it's a hb problem, it should be present in all the orders. I will do more testing about it. If you can specify or understand when this is happening or if you can track the order id in the market and see if it's placed or if it was placed in the past, will be useful!

**Comment by raymondcarl** [comment] 2022-09-12 19:07
@cardosofede: From what I've seen, the order is actually placed on the exchange and is cancelled ok. The problem is that the current state of order tracking used by the strategy does not show it as cancelled. That's the best I can see what it happening.

**Comment by cardosofede** [comment] 2022-09-12 19:13
@raymondcarl nice! Yes probably there is a bug in the order tracker of the strategy, I will check it now. It's strange because it's only happening in perpetuals and with Binance but well.
All of you are using perpetuals market making?

**Comment by raymondcarl** [comment] 2022-09-12 19:31
@cardosofede : Yes, binance perpetuals for me. That's why I was saying that I think this could be a very difficult problem to find because in theory, it should affect all the strategies. I think it could also be something in the binance derivative connector that is failing intermittently to update the order state that the strategy uses.

**Comment by cardosofede** [comment] 2022-09-12 22:20
I think that I found something!
In Flight Orders from the connector:


![Image](https://user-images.githubusercontent.com/36869960/189768370-c3831692-453e-41d5-b61c-3318c0542a50.png)

Active orders from the OrderTracker:


![Image](https://user-images.githubusercontent.com/36869960/189768556-7b2e0ac1-71a3-4a5a-8bf2-20d9612191cf.png)

Tomorrow I will continue with the research ! Hope that I can solve this soon.

**Comment by leastchaos** [comment] 2022-09-12 22:51
> @raymondcarl nice! Yes probably there is a bug in the order tracker of the strategy, I will check it now. It's strange because it's only happening in perpetuals and with Binance but well. All of you are using perpetuals market making?

@cardosofede this impacts all strategy that uses binance_perpetual not just perpetual market making strategy. This is happening with other strategy such as hedge too. It should be an issue related to binance_perpetual connector only.

**Comment by amitds1997** [comment] 2022-09-13 06:01
I am also trying to debug this issue and I am able to replicate the issue almost every 2-3 hours running my strategy on binance testnet. For me, the order with the issue has order ID: x-3QreWesyBBCUT5e880e5dafe1fc81f.

What I found out was that the `market.event_logs` list has captured an `OrderCancelledEvent(timestamp=1663015193.0, order_id='x-3QreWesyBBCUT5e880e5dafe1fc81f', exchange_order_id='3211161019')` and in the tracker object, the order is still in `in_flight_cancels`.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/29333147/189821246-a6a4b87e-bd1f-4f60-a86c-024ce1f8e71a.png">
Event log has received the order cancel event.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/29333147/189821270-e427bf08-51ee-4d58-a17b-7fee2974f7f5.png">
in_flight_cancels has not got the order removed. (The custom tracker name is just an alias right now for the underlying tracker, no modifications or enhancements added)

**Comment by amitds1997** [comment] 2022-09-13 06:58
I am also trying to debug this issue on my end.

**My observations:** 
1.  The order is present in `self._sb_order_tracker.in_flight_cancels` but not present in `self._market_info.market.in_flight_orders`. 
2. The `active_orders` property depends upon `market_pair_to_active_orders` and the logic for that is different b/w `PerpetualMarketMakingOrderTracker` and the base `OrderTracker`

```python
# In PerpetualMarketMakingOrderTracker
    @property
    def market_pair_to_active_orders(self) -> Dict[MarketTradingPairTuple, List[LimitOrder]]:
        market_pair_to_orders = {}
        for market_pair, orders_map in self.tracked_limit_orders_map.items():
            market_pair_to_orders[market_pair] = list(self.tracked_limit_orders_map[market_pair].values())
        return market_pair_to_orders

# In OrderTracker
    @property
    def market_pair_to_active_orders(self) -> Dict[MarketTradingPairTuple, List[LimitOrder]]:
        market_pair_to_orders = {}
        market_pairs = self._tracked_limit_orders.keys()
        for market_pair in market_pairs:
            limit_orders = []
            for limit_order in self._tracked_limit_orders[market_pair].values():
                if self.c_has_in_flight_cancel(limit_order.client_order_id):
                    continue
                limit_orders.append(limit_order)
            market_pair_to_orders[market_pair] = limit_orders
        return market_pair_to_orders
```
If `PerpetualMarketMakingOrderTracker.market_pair_to_active_orders` had the same logic, I can see how we would not face this issue because the order is still in `in_flight_cancel`.

**Comment by cardosofede** [comment] 2022-09-13 11:43
@amitds1997 yes you are right, I check that too yesterday.
Also I found that the binance perpetuals class has a lot of errors when asking information to the order tracker.

**Comment by raymondcarl** [comment] 2022-09-13 14:06
The class hierarchy for this whole application has been very confusing for me due. I created this so that I don't have to keep looking for the references over and over.
![Hummingbot](https://user-images.githubusercontent.com/9866425/189922384-c70a6bd0-defa-46b2-9a2b-3df241ad1039.jpg)

**Comment by raymondcarl** [comment] 2022-09-13 16:38
One thing I see that seems strange to me is that the binance perpetual connector does not implement the OrderCancellation event like bitmex does. Is it possible that the order cancellation event is how stop_tracking_limit_order is triggered?

**Comment by amitds1997** [comment] 2022-09-13 16:38
As far as I could find so far, it's the `market` component. 
1. Calling `self.cancel_order` calls StrategyBase's `cancel_order` which calls the market connector's `c_cancel` method. ([source](https://github.com/hummingbot/hummingbot/blob/master/hummingbot/strategy/strategy_base.pyx#L587-L599)).
2. This will call `BinancePerpetualDerivative`'s `cancel` method internally for our use case ([source](https://github.com/hummingbot/hummingbot/blob/master/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py#L371-L385))
3. The `_execute_cancel` method calls `self.stop_tracking_order(order_id)` which cleans up the order tracker for the market component ([source](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py#L1309-L1351)).

So, the order tracker for the market has been cleaned up but somehow it missed clearing up the strategy's order tracker.

**Comment by raymondcarl** [comment] 2022-09-13 16:47
@amitds1997 : Yes, I agree on the process for the actual cancellation of the order. For the strategy's order tracker though, I think something has to call stop_tracking_limit_order for the strategy in order to reflect the cancellation. I can't find that anywhere after searching throughout the repository. I don't think that this is the issue, but if I can find out what is calling that method, I think it will be pretty quick to find the problem.

The only other idea right now is that the [OrderCancelled](https://github.com/hummingbot/hummingbot/blob/433df629f3a486a1b6e83bfd8a19493ba20e7e85/hummingbot/core/event/events.py) event some how triggers this.

**Comment by raymondcarl** [comment] 2022-09-13 17:03
Ok, now this is starting to make more sense to me. A big question for me now is, "why are any orders at all reflected as canceled if the binance perpetual connector does not implement the order cancelled event?"
![Hummingbot(4)](https://user-images.githubusercontent.com/9866425/189963010-aedf6c42-6c24-467e-ad7b-52a395dbdf3a.jpg)

**Comment by raymondcarl** [comment] 2022-09-13 17:08
I'm going to implement the order cancellation event in the binance perpetual connector locally and let it run while I try to understand how the strategy's version of of the order state can reflect the correct state even before it gets stuck in the loop.

**Comment by cardosofede** [comment] 2022-09-13 17:10
@raymondcarl @amitds1997 I found the error, the issue is in the connector. I will provide a solution for today

**Comment by amitds1997** [comment] 2022-09-13 17:30
> @amitds1997 : Yes, I agree on the process for the actual cancellation of the order. For the strategy's order tracker though, I think something has to call stop_tracking_limit_order for the strategy in order to reflect the cancellation. I can't find that anywhere after searching throughout the repository. I don't think that this is the issue, but if I can find out what is calling that method, I think it will be pretty quick to find the problem.
> 
> The only other idea right now is that the [OrderCancelled](https://github.com/hummingbot/hummingbot/blob/433df629f3a486a1b6e83bfd8a19493ba20e7e85/hummingbot/core/event/events.py) event some how triggers this.

Okie, I think I figured out how it is working out:

1. Strategy issues a `cancel_order` call.
2. This gets routed to the `market.cancel` method which calls `_execute_cancel` asyncronously. It calls the Binance Perp cancel API until Binance returns a `-2011` HTTP response.
3. When this happens, the `stop_tracking_order` is called which cleans up the market client_order_tracker correctly. ([source](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py#L1344-L1347))
4. The websocket gets an order cancelled event from Binance. (This is the contention point, if we correctly received the message or not).
5. The `BinancePerpetualDerivative` event loop calls the async `_process_user_stream_event` which calls the client_order_tracker's `process_order_update` ([source](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py#L651-L702)).
6. This calls `_trigger_order_completion` for the cancelled order ([source](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/connector/client_order_tracker.py#L198-L223)).
7. This calls the `_trigger_cancelled_event` which generates the `OrderCancelledEvent` internally. ([source](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/connector/client_order_tracker.py#L251-L259)).
8. `StrategyBase`'s `OrderCancelledListener`: `self._sb_cancel_order_listener` which calls `c_call` function. ([source#1](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/strategy/strategy_base.pyx#L148), [source#2](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/strategy/strategy_base.pyx#L70-L73))
9. This calls `c_did_cancel_order_tracker` which calls `c_stop_tracking_limit_order`. ([source](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/strategy/strategy_base.pyx#L469-L474)).
10. This updates the strategy's order tracker.

**Comment by raymondcarl** [comment] 2022-09-13 18:22
> The websocket gets an order cancelled event from Binance. (This is the contention point, if we correctly received the message or not).

Yes, that could be problem. In the cycle you describe, it would work under normal conditions, but if the websocket was temporarily disconnected or something, the only way that the strategy's version of the outstanding orders would be updated is if the OrderCancelledEvent is generated when the _execute_cancel's call to binance returns an error. It looks to me like if that cycle you mention above ever has a problem with the websocket connection, there is no way for c_stop_tracking_limit_order to ever be triggered.

I have added a OrderCancelledEvent locally to _execute_cancel. So far, it has been working for about 1 hour, which is longer than the average.

**Comment by raymondcarl** [comment] 2022-09-13 18:32
Nope, now the issues is back :/

**Comment by raymondcarl** [comment] 2022-09-13 18:52
This is what I'm testing locally now
![image](https://user-images.githubusercontent.com/9866425/189986039-5c9a4f1a-871d-42db-9a59-ab79fb004a80.png)

**Comment by raymondcarl** [comment] 2022-09-14 06:40
I let it run overnight, and so far, it's still working without entering the loop. This is the longest it has ever run for me. Will let it keep running and try to let it for a full 2 days to make sure this problem is really gone.

**Comment by cardosofede** [comment] 2022-09-14 08:45
@raymondcarl you can check the pr that I sent to see the solution. It's using a method to process the order not found because that's the message.
However if you want to just cancel the order as are you doing, you should use the method to process the order updates from the client order tracker to make the code more clean, because we have already that logic implemented

**Comment by leastchaos** [comment] 2022-09-20 01:09
I think I determined the actual root cause of the issue.
the latest pr does not fully solve the problem.
After 1 hour, the balance does not update in real-time, and orders are required to cancel 3 times in order to be actually canceled.

It is actually missing is_auth in the ping listen key. 
after this fix, there are no more multiple cancel orders and the balance is back to real-time.
It was erratic for me because if you start another binance perpetual connector before the 1-hour mark, it will also help to refresh the listen key of the current one. so it would not always stop listening for events after 1 hour.

![image](https://user-images.githubusercontent.com/64965782/191145081-107627fd-a1f1-4f28-b5e6-7407cd91bd76.png)

https://github.com/hummingbot/hummingbot/issues/5713

**Comment by cardosofede** [comment] 2022-09-20 01:43
I will review it tomorrow and get back to you.
However I think that are different issues, one is related to the process of
the events + order updates and the other one is related to the listen key.
The strange thing is that the QA team run a perp market making for 2 days
without issues.

**Comment by leastchaos** [comment] 2022-09-20 02:03
Ok thanks.
Just some notes,
1. The balance, positions, and orders eventually match the exchange after some seconds. 
2. Canceling orders also mostly happens 3 times in a row once it starts happening but it will also eventually cancel. 
The data are always eventually consistent with exchange after some time but these are not updated in real-time which I think is due to the updates maintained by the rest endpoint instead of the WebSocket.

**Comment by rapcmia** [comment] 2022-09-30 02:52
Fixed on development branch but there are noticeable issues found which will be fix on another PR. Thank you

**Closed by rapcmia** 2022-09-30 02:52 UTC
Labels: P2, bug, binance_perpetual, perpetual_market_making, staging, bounty_hbot, Medium
