### ISSUE TITLE
Exception when starting HB with gateway certificates not found

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#5804] opened 2022-10-14 16:15 UTC
**Describe the bug**
An exception is called upon starting latest HB dev-1.9.0 related to the gateway - This does not seem to hamper using HB with DEX

**Steps To Reproduce**
Start the bot and observe the log:
```
2022-10-11 16:11:57,314 - 3133524 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/memento/PycharmProjects/hummingbot-dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/memento/PycharmProjects/hummingbot-dev/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 249, in load_token_data
    tokens = await GatewayHttpClient.get_instance().get_tokens(self.chain, self.network)
  File "/home/memento/PycharmProjects/hummingbot-dev/hummingbot/core/gateway/gateway_http_client.py", line 296, in get_tokens
    return await self.api_request("get", "network/tokens", {
  File "/home/memento/PycharmProjects/hummingbot-dev/hummingbot/core/gateway/gateway_http_client.py", line 175, in api_request
    client = self._http_client(self._client_config_map)
  File "/home/memento/PycharmProjects/hummingbot-dev/hummingbot/core/gateway/gateway_http_client.py", line 83, in _http_client
    ssl_ctx = ssl.create_default_context(cafile=f"{cert_path}/ca_cert.pem")
  File "/home/memento/.conda/envs/hummingbot/lib/python3.8/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory
```

Here are the steps to reproduce the issue (see attachments in the section below):
1. Start the bot using this command: `./bin/hummingbot_quickstart.py -p xxx`
...

**Screenshots**
![image](https://user-images.githubusercontent.com/93164135/195892931-5d6aeb50-33ac-49b3-af61-fd8879cf5c2c.png)

**Release version**
dev-1.9.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment] 2022-10-17 03:43
Hi @MementoRC good day to you,
We tried to replicate this issue but can't reproduce atm using the development branch commit `539a1a61706f3..` using the steps to reproduce. Please see the screen recording below:

Ran `/bin/hummingbot_quickstart.py -p xxx` or `python3 bin/hummingbot_quickstart.py -p password`

https://user-images.githubusercontent.com/73840223/196084406-36bbe4cc-acea-4c43-808f-44a3cee583c8.mp4

Ran also with working AMM strategy `python3 bin/hummingbot_quickstart.py -f config_strategy.yml -p password`

https://user-images.githubusercontent.com/73840223/196084592-a31a6ebe-dd17-4eb2-af39-2180ded6733d.mp4

This seems to be working as expected however let us know if anything we have missed so we can further look this with you. Thanks for your time for creating this ticket 👍

**Comment by MementoRC** [comment] 2022-10-17 16:27
@rapcmia I think the issue could be that I created several versions of the gateway, so I have several gateway credentials directories. HB somehow tries to access one that is not valid. It is possible that if I do a `gateway create` the error will go away. However, I was creating this issue to raise attention that we could add some verification of the path rather than emit an exception

**Comment by MementoRC** [comment] 2022-10-17 17:22
@rapcmia We can close if this does not look like a bug, thx

**Comment by rapcmia** [comment] 2022-10-18 04:48
Hi @MementoRC thanks for update, our gateway v2 is still in development and will discuss this with the team as a possible improvement. Yes we can close this for now and we can reopen if needed for further tests. Thank you for your time!

**Closed by rapcmia** 2022-10-18 04:48 UTC
Labels: bug

**Comment by MementoRC** [comment] 2022-10-27 21:36
@rapcmia Update on the origin: It is inferred from the `instance_id`  in the conf_client.yml. I must have updated this at some point and forgot - Completely closed now
