### ISSUE TITLE
[BUG] Windows binary v.0.33.0 error connecting loopring

### ISSUE THREAD

**Issue by CalicaliT** [hummingbot/hummingbot#2614] opened 2020-11-12 19:06 UTC
**Describe the bug**
Adding Loopring API key shows error - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No module named 'ethsnarks_loopring' Traceback (most recent call last):

Also loops on "Enter your loopring API key" CTRL + X can not exit config

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Install v. 0.33.0 Windows binary
1. Connect loopring

**Screenshots**
![image](https://user-images.githubusercontent.com/71769411/98984236-e38fc080-255c-11eb-8c3d-2601754843bb.png)
![image](https://user-images.githubusercontent.com/71769411/98984251-ee4a5580-255c-11eb-8268-48136269db9f.png)

**Release version**
v. 0.33.0

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5532693/logs_hummingbot.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1raktac) by [Unito](https://www.unito.io)

**Comment by glenntomas** [comment] 2020-11-13 12:49
Encountered the same issue

![loopring issue](https://user-images.githubusercontent.com/73885708/99073786-7da14880-25f1-11eb-89d0-6d9301c5e682.PNG)

**Comment by mhairimca** [comment] 2020-11-16 12:30
I also have this issue.

**Comment by plpippen** [comment] 2021-01-07 18:52
I am also having the same issue

**Comment by glenntomas** [comment] 2021-04-22 05:14
**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Install v0.38.1 binary installer
2. Connect Loopring

**Screenshots**

![image](https://user-images.githubusercontent.com/73885708/115658968-63bc1c80-a36c-11eb-82c5-064977ad2007.png)

```
2021-04-22 12:59:55,352 - 17260 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No module named 'ethsnarks_loopring'
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\connect_command.py", line 63, in connect_exchange
  File "hummingbot\user\user_balances.py", line 53, in add_exchange
  File "hummingbot\user\user_balances.py", line 24, in connect_market
  File "hummingbot\client\config\config_helpers.py", line 208, in get_connector_class
  File "hummingbot\connector\exchange\loopring\loopring_exchange.pyx", line 55, in init hummingbot.connector.exchange.loopring.loopring_exchange
ModuleNotFoundError: No module named 'ethsnarks_loopring'
```

**Release Version**
v0.38.1

**Discord Handle**
Regex_Philbin

**Comment by DeFiDinosaur** [comment] 2021-04-23 21:41
Same issue:  async_utils - Unhandled error in background task: No module named 'ethsnarks_loopring' (See log file for stack trace dump)

There's dozens of us!  Anyone have a solution?

**Comment by rapcmia** [comment] 2022-02-01 06:53
Closing ticket since Binary has been removed on Hummingbot version 1.0.0

**Closed by rapcmia** 2022-02-01 06:53 UTC
Labels: P2, bug, loopring
