### ISSUE TITLE
Gate_io - Message Spam 'Performance-could not find exchange rate'

### ISSUE THREAD

**Issue by hbminerfan** [hummingbot/hummingbot#6330] opened 2023-05-25 08:03 UTC
**Describe the bug**
Running Pure Market Making strategy at Gate_io, there is constant message spam: 

"performance - could not find exchange rate for (market pair) using binance rate oracle. PNL value will be inconsistent."

This message shows in whatever market pair. Did not change any parameter for rate oracle. I prefer this message not be shown by default as it obstructs other important info such as order placements.

**Steps To Reproduce**
1. Create strategy using Pure Market Making strategy
2. Run the strategy using any market pair
3. Observe the right pane where the message spam will occur after few minutes
...

**Screenshots**
![Screenshot 2023-05-25 154717_GateIO](https://github.com/hummingbot/hummingbot/assets/134588875/54532a2a-c736-4784-abe6-81b289728851)

**Release version**
v1.15

**Comment by nikspz** [comment] 2023-05-25 10:01
hi @hbminerfan Could you please send here your config file/screenshot? 
I tried, but can't reproduce your issue. Did you tried to change rate oracle source to gate.io with `config rate_oracle_source` command?

![image](https://github.com/hummingbot/hummingbot/assets/83953535/27537b07-5066-49f5-b6e0-4f23ae685349)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/f5d788c1-ccd7-44c5-ac13-c82a44001b84)

**Comment by nikspz** [comment] 2023-05-31 07:30
closing this issue as could not reproduced/no answer from user

**Closed by nikspz** 2023-05-31 07:30 UTC
Labels: bug, gate_io
