### ISSUE TITLE
Fee override not working for exchanges that estimate fee on fills and not getting the data from the exchange info

### ISSUE THREAD

**Issue by rolandgem** [hummingbot/hummingbot#5089] opened 2022-02-03 13:26 UTC
**Describe the bug**
- I am using NDAX exchange, which charges a constant percentage fee of 0.2% on both maker and taker trades.
- I want to override the fee so in the file `conf_fee_overrides.yml`, I changed `ndax_maker_percent_fee = 0.1` and `ndax_taker_percent_fee = 0.1`.
- After I save the file and run the bot, these new values are not reflected in the performance section under `history` command.
- Even when setting these values to 0, I still get a fee that is calculated.
- in version 0.46 I did not have this issue, only in v 1.0.0

**Steps To Reproduce**
- In `conf_fee_overrides.yml` change `ndax_maker_percent_fee = 0.0` and `ndax_taker_percent_fee = 0.0`.
- Run the bot.
- Run the `history` command
- You should get $0 for Fees, or this should not even show up in the performance section (as was the case in v 0.46).

**Release version**
V 1.0.0

**Comment by rapcmia** [comment] 2022-03-30 08:19
Hi @rolandgem good day,
I think this is expected behavior for the fees override feature of the client. By default it uses the fees of the exchange however if your account is on a different tier, this feature should be able you to modify fees under `conf_fee_overrides.yml` else it would just revert the changes back to a blank (default) 

Here's the link to docs about [Fee override](https://hummingbot.org/global-configs/override-fees/)

**Comment by rapcmia** [comment] 2022-04-27 08:41
Closing ticket since NDax takes the fees directly from exchange. Fees override would normally work for connectors with estimated fees however we have reported an issue found in #5210

**Closed by rapcmia** 2022-04-27 08:41 UTC
Labels: bug
