### ISSUE TITLE
FTX- Error in requesting exchange info

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5883] opened 2022-11-14 07:11 UTC
**Describe the bug**
Upon opening the hummingbot client, we are getting a notification regarding FTX `There was an error requesting exchange info` d

Note: This does not affect other connectors

![image](https://user-images.githubusercontent.com/73840223/201596737-0aeea7a7-a774-43d2-a720-987e85d377e4.png)

```
2022-11-14 15:08:34,948 - 6346 - hummingbot.connector.exchange.ftx.ftx_exchange.FtxExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/connector/exchange_py_base.py", line 1018, in _initialize_trading_pair_symbol_map
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/rapcmia/github/dev/hummingbot/connector/exchange_py_base.py", line 845, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/rapcmia/github/dev/hummingbot/connector/exchange_py_base.py", line 878, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://ftx.com/api/markets. HTTP status is 503. Error: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"769deacdef53b9f3","token":"7a17a4f473fb4f15a21c9ed7ec04e38d","version":"2022.11.0","si":100}' crossorigin="anonymous"></script>
</body>
</html>
```

**Steps To Reproduce**
1. Open hummingbot client

**Release version**
development branch

**Comment by mhrvth** [comment] 2022-11-14 23:01
Obviously since the exchange is bankrupt the service is terminated. It's not a bug.

**Comment by nikspz** [comment] 2022-11-23 15:12
Will close the issue since Ftx is going to be deleted in 1.10.0 Release

**Closed** 2022-11-25 06:35 UTC
Labels: bug, ftx, wontfix
