### ISSUE TITLE
OKX - False 'insufficient balance' error occurs when submitting a market order to close a position, causing asset imbalance

### ISSUE THREAD

**Issue by AlexeyBoiler** [hummingbot/hummingbot#7127] opened 2024-07-14 22:07 UTC
### Describe the bug

XEMM v2 strategy bot 2.0.0 works with 2 connectors: binance maker and okx taker; when an order is activated on the maker, the order for rebalancing does not take place on the tacker. There was no such error before.

Client failed to check balance is sufficient

### Steps to reproduce

1. 
2. 
3. 

### Release version

2.0.0

### Type of installation

Docker

**Comment by rapcmia** [comment] 2024-07-15 12:31
Hi @AlexeyBoiler I have some results on my tests where the taker(okx) return insufficient balance after maker got filled when I have enough to place the order. Im running a different setup again see if I can reproduce this behvior or different. 

We would appreciate if you would attach the logs files the next time you post the issue so we can compare and investigate. Thank you

**Comment by AlexeyBoiler** [comment] 2024-07-15 12:41
Here is his answer:

```
My results, for some reason Client failed to check balance is sufficient

Flow was like this, 
```
![image-22](https://github.com/user-attachments/assets/3ffcce16-3a83-4f76-aa28-4a03eaa98a26)

**Comment by rapcmia** [comment] 2024-07-15 12:51
> Hi. @rapcmia My problem was confirmed by Nikita from your team, but for some reason he did not write about this bug in Github. I decided to remind you.

Thanks for the update @AlexeyBoiler, I get the same error earlier as well
```

# Creating / Created sell order SNTUT61d4454ef49315dcdb00972e39ba6478e6f
2024-07-15 07:39:40,213 - 521191 - hummingbot.strategy.script_strategy_base - INFO - Creating NOT-USDT sell order: price: 0.01686659295542001068719384106 amount: 932.5400525952589663726057034.
2024-07-15 07:39:40,213 - 521191 - hummingbot.strategy_v2.executors.xemm_executor.xemm_executor - INFO - Created maker order SNTUT61d4454ef49315dcdb00972e39ba6478e6f at price 0.01686659295542001068719384106.
2024-07-15 07:39:40,474 - 521191 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order SNTUT61d4454ef49315dcdb00972e39ba6478e6f for 932 NOT-USDT.
2024-07-15 07:39:40,474 - 521191 - hummingbot.strategy_v2.executors.xemm_executor.xemm_executor - INFO - Maker order SNTUT61d4454ef49315dcdb00972e39ba6478e6f created.
2024-07-15 07:39:40,495 - 521191 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721029180.0, "type": "OrderType.LIMIT", "trading_pair": "NOT-USDT", "amount": "932", "price": "0.0168665", "order_id": "SNTUT61d4454ef49315dcdb00972e39ba6478e6f", "creation_timestamp": 1721029180.0, "exchange_order_id": "6694d23c5677640007c812a4", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "kucoin"}

# Sell SNTUT61d4454ef49315dcdb00972e39ba6478e6f has been filled 
2024-07-15 07:39:52,787 - 521191 - hummingbot.connector.client_order_tracker - INFO - The SELL order SNTUT61d4454ef49315dcdb00972e39ba6478e6f amounting to 932/932 NOT has been filled.
2024-07-15 07:39:52,815 - 521191 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721029192.0, "order_id": "SNTUT61d4454ef49315dcdb00972e39ba6478e6f", "trading_pair": "NOT-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": "0.0168665", "amount": "932", "trade_fee": {"percent": "0.001", "percent_token": null, "flat_fees": []}, "exchange_trade_id": "4949445769171086", "exchange_order_id": "6694d23c5677640007c812a4", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "kucoin"}
2024-07-15 07:39:52,827 - 521191 - hummingbot.strategy_v2.executors.xemm_executor.xemm_executor - INFO - Maker order SNTUT61d4454ef49315dcdb00972e39ba6478e6f completed. Executing taker order.
2024-07-15 07:39:52,827 - 521191 - hummingbot.strategy.script_strategy_base - INFO - Creating NOT-USDT buy order: price: NaN amount: 932.5400525952589663726057034.
2024-07-15 07:39:52,841 - 521191 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721029192.0, "order_id": "SNTUT61d4454ef49315dcdb00972e39ba6478e6f", "base_asset": "NOT", "quote_asset": "USDT", "base_asset_amount": "932", "quote_asset_amount": "15.7195780", "order_type": "OrderType.LIMIT", "exchange_order_id": "6694d23c5677640007c812a4", "event_name": "SellOrderCompletedEvent", "event_source": "kucoin"}
2024-07-15 07:39:52,841 - 521191 - hummingbot.connector.client_order_tracker - INFO - SELL order SNTUT61d4454ef49315dcdb00972e39ba6478e6f completely filled.
2024-07-15 07:39:53,877 - 521191 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error submitting buy MARKET order to Okx for 932.5 NOT-USDT NaN.
Traceback (most recent call last):
  File "/home/rapcomia/github/hummingbot/development/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/rapcomia/github/hummingbot/development/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/rapcomia/github/hummingbot/development/hummingbot/connector/exchange/okx/okx_exchange.py", line 208, in _place_order
    raise IOError(f"Error submitting order {order_id}: {data['sMsg']}")
OSError: Error submitting order 93027a12dac34fBCBNTUTbe9598046fe: Order failed. Insufficient USDT balance in account. 
2024-07-15 07:39:53,884 - 521191 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to submit BUY order to Okx. Check API key and network connection.
2024-07-15 07:39:53,912 - 521191 - hummingbot.strategy.script_strategy_base - INFO - Creating NOT-USDT buy order: price: NaN amount: 932.5400525952589663726057034.
2024-07-15 07:39:53,912 - 521191 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721029193.0, "order_id": "93027a12dac34fBCBNTUTbe9598046fe", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
2024-07-15 07:39:53,912 - 521191 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBNTUTbe9598046fe has failed. Order Update: OrderUpdate(trading_pair='NOT-USDT', update_timestamp=1721029193.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBNTUTbe9598046fe', exchange_order_id=None, misc_updates=None)
2024-07-15 07:39:54,430 - 521191 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error submitting buy MARKET order to Okx for 932.5 NOT-USDT NaN.
Traceback (most recent call last):
  File "/home/rapcomia/github/hummingbot/development/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/rapcomia/github/hummingbot/development/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/rapcomia/github/hummingbot/development/hummingbot/connector/exchange/okx/okx_exchange.py", line 208, in _place_order
    raise IOError(f"Error submitting order {order_id}: {data['sMsg']}")
OSError: Error submitting order 93027a12dac34fBCBNTUTe560a12d4da: Order failed. Insufficient USDT balance in account. 
2024-07-15 07:39:54,431 - 521191 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to submit BUY order to Okx. Check API key and network connection.

# Buy market order on taker market failed due to insufficient balance?
```

**Comment by rapcmia** [comment] 2024-07-17 16:07
Able to reproduce some instances of this issue using `pmm_simple` controller for OKX spot

Started with each have enough balance to place orders 
![image](https://github.com/user-attachments/assets/1128c3ab-dfa5-4fd1-ba04-96540e282154)

Ended the script with imbalance assets
![image](https://github.com/user-attachments/assets/bdc97ce6-c242-4f1d-91fa-0430e35bb360)

Log file with comment
```
# Creating / Created Sell order 93027a12dac34fBCSNTUT66b29da5c05
2024-07-17 21:28:09,731 - 32458 - hummingbot.strategy.script_strategy_base - INFO - Creating NOT-USDT buy order: price: 0.01584868799999999999733937828 amount: 1577.417638608318871833233870.
2024-07-17 21:28:09,733 - 32458 - hummingbot.strategy.script_strategy_base - INFO - Creating NOT-USDT sell order: price: 0.01610431200000000000266062173 amount: 1552.379263392313809858484237.
2024-07-17 21:28:09,800 - 32458 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 93027a12dac34fBCSNTUT66b29da5c05 for 1552.3 NOT-USDT.
2024-07-17 21:28:09,801 - 32458 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721222889.0, "type": "OrderType.LIMIT", "trading_pair": "NOT-USDT", "amount": "1552.3", "price": "0.016104", "order_id": "93027a12dac34fBCSNTUT66b29da5c05", "creation_timestamp": 1721222889.0, "exchange_order_id": "1634788368576036865", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "okx"}
2024-07-17 21:28:09,815 - 32458 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order 93027a12dac34fBCBNTUT24f33bd66dd for 1577.4 NOT-USDT.
2024-07-17 21:28:09,815 - 32458 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721222889.0, "type": "OrderType.LIMIT", "trading_pair": "NOT-USDT", "amount": "1577.4", "price": "0.015848", "order_id": "93027a12dac34fBCBNTUT24f33bd66dd", "creation_timestamp": 1721222889.0, "exchange_order_id": "1634788368576036864", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "okx"}

# Filled sell order 93027a12dac34fBCSNTUT66b29da5c05 and opened executors
# Creatnig / Created limit buy close order 93027a12dac34fBCBNTUTa22badeefa2 and cancelled @2024-07-17 21:59:11,040
# Creating market buy close order but failed due to insufficient balance? retry logic started until @2024-07-17 21:59:19,944
2024-07-17 21:35:04,305 - 32458 - hummingbot.connector.client_order_tracker - INFO - The SELL order 93027a12dac34fBCSNTUT66b29da5c05 amounting to 1552.3/1552.3 NOT has been filled.
2024-07-17 21:35:04,307 - 32458 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721223304.0, "order_id": "93027a12dac34fBCSNTUT66b29da5c05", "trading_pair": "NOT-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": "0.016104", "amount": "1552.3", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "-0.01999859136"}]}, "exchange_trade_id": "34329862", "exchange_order_id": "1634788368576036865", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "okx"}
2024-07-17 21:35:04,366 - 32458 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721223304.0, "order_id": "93027a12dac34fBCSNTUT66b29da5c05", "base_asset": "NOT", "quote_asset": "USDT", "base_asset_amount": "1552.3", "quote_asset_amount": "24.9982392", "order_type": "OrderType.LIMIT", "exchange_order_id": "1634788368576036865", "event_name": "SellOrderCompletedEvent", "event_source": "okx"}
2024-07-17 21:35:04,370 - 32458 - hummingbot.connector.client_order_tracker - INFO - SELL order 93027a12dac34fBCSNTUT66b29da5c05 completely filled.
2024-07-17 21:35:05,258 - 32458 - hummingbot.strategy.script_strategy_base - INFO - Creating NOT-USDT buy order: price: 0.01594296 amount: 1552.3.
2024-07-17 21:35:05,349 - 32458 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order 93027a12dac34fBCBNTUTa22badeefa2 for 1552.3 NOT-USDT.
2024-07-17 21:35:05,350 - 32458 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721223305.0, "type": "OrderType.LIMIT", "trading_pair": "NOT-USDT", "amount": "1552.3", "price": "0.015942", "order_id": "93027a12dac34fBCBNTUTa22badeefa2", "creation_timestamp": 1721223305.0, "exchange_order_id": "1634802312019591168", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "okx"}
2024-07-17 21:58:10,574 - 32458 - hummingbot.strategy.script_strategy_base - INFO - (NOT-USDT) Canceling the limit order 93027a12dac34fBCBNTUT24f33bd66dd. [clock=2024-07-17 13:58:10+00:00]
2024-07-17 21:58:10,625 - 32458 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721224690.0, "order_id": "93027a12dac34fBCBNTUT24f33bd66dd", "exchange_order_id": "1634788368576036864", "event_name": "OrderCancelledEvent", "event_source": "okx"}
2024-07-17 21:58:10,637 - 32458 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCBNTUT24f33bd66dd.
...trimmed from log file

2024-07-17 21:59:19,858 - 32458 - hummingbot.strategy.script_strategy_base - INFO - Creating NOT-USDT buy order: price: NaN amount: 1552.3.
2024-07-17 21:59:19,941 - 32458 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error submitting buy MARKET order to Okx for 1552.3 NOT-USDT NaN.
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/7121/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/Users/rapcomia/github/hummingbot/7121/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/Users/rapcomia/github/hummingbot/7121/hummingbot/connector/exchange/okx/okx_exchange.py", line 208, in _place_order
    raise IOError(f"Error submitting order {order_id}: {data['sMsg']}")
OSError: Error submitting order 93027a12dac34fBCBNTUT7f130c4bbd4: Order failed. Insufficient USDT balance in account. 
2024-07-17 21:59:19,942 - 32458 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to submit BUY order to Okx. Check API key and network connection.
2024-07-17 21:59:19,944 - 32458 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1721224759.0, "order_id": "93027a12dac34fBCBNTUT7f130c4bbd4", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
2024-07-17 21:59:19,944 - 32458 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Close order failed. Retrying 11/10
2024-07-17 21:59:19,944 - 32458 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBNTUT7f130c4bbd4 has failed. Order Update: OrderUpdate(trading_pair='NOT-USDT', update_timestamp=1721224759.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBNTUT7f130c4bbd4', exchange_order_id=None, misc_updates=None)
```
- After opening a executor, the connector failed to submit a close market order causing the retry feature to occur however failed to complete. This resulted to imbalance assets.
- Another instance can be found on the log file below with added comments and controller used 
- The trade data on csv matched from exchange's trade history ✅ 

[07172024.zip](https://github.com/user-attachments/files/16269261/07172024.zip)

**Comment by nikspz** [comment] 2024-07-22 13:16
Bounty:
Sponsor: Hummingbot Foundation
Bounty amount: 50K HBOT
Developer portion: 50K HBOT

**Comment by Jbekker** [comment] 2024-07-23 08:26
I'm happy to take a look at this over the next days / upcoming weekend.

**Comment by nikspz** [comment] 2024-07-23 09:35
Assigned to @Jbekker, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment] 2024-08-16 14:14
hi @Jbekker Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by nikspz** [comment] 2024-09-04 05:52
Thanks for your participation, the bounty has been sent to @Jbekker . The fix has been deployed on development branch and hummingbot version 2.0.1

**Closed by nikspz** 2024-09-04 05:52 UTC
Labels: P2, bug, okx, v2_strategies
