### ISSUE TITLE
AMM Arbitrage strategy stuck on "waiting for allowances" on Arbitrum

### ISSUE THREAD

**Issue by Albonida** [hummingbot/hummingbot#5926] opened 2022-12-05 13:31 UTC
**Describe the bug**

when launching amm_arb strategy receive the following error: "uniswap_ethereum_arbitrum_one not ready: waiting for allowance"

**Steps To Reproduce**
create amm_arb
first connector binance
second connector uniswap_ethereum_arbitrum_one

pair traded WBTC-ETH
parameters can be  WBTC traded 0.0001, profitability 0.001, slippage a 0.1, slippage b 0.1

**Screenshots**
<img width="647" alt="Screenshot 2022-12-05 at 21 26 03" src="https://user-images.githubusercontent.com/119740434/205649279-2871a38b-14b2-4d01-844d-450a3c1668d2.png">

**Release version**
1.10.0

**Comment by nikspz** [comment] 2022-12-09 11:33
Upon checking I was able to do the trades on other trading pair (changed `Infura NodeURL for arbitrum_one` )

![image](https://user-images.githubusercontent.com/83953535/206693387-c015c935-1d07-4f3e-8ee3-083a45781b25.png)

The issue is your pair not exist in the current tokenlist bot use, so you could try to change add manually

**Comment by Albonida** [comment] 2022-12-09 11:37
Thanks a lot! Will try

May I ask you:
- how do i see trading pair list?
- how can I add one manually?

Thanks!

**Comment by rapcmia** [comment] 2022-12-12 16:44
Hi @Albonida good day to you
Apologies for the late response,  by running command `gateway config ethereum.networks.arbitrum_one` and look for `tokenListSource` this is where gateway would normally check the tokens supported by the connector. Atm the moment here is the default for our Uniswap arbitrum [link](https://bridge.arbitrum.io/token-list-42161.json)

Adding manually is a different setup as you would need to:
1. Create a local json file and save it under `../gateway/src/chains/ethereum/...` and add the missing token you want to use by adding their token address. 
2. Open the hummingbot client (make sure its connected to gateway) and run `gateway config ethereum.networks.arbitrum_one.tokenListSource src/chains/ethereum/name-of-file.json` 
3. Gateway will update and reconnect

On this issue I think this is the expected behavior since it would need you to wrap your ETH (wETH) and it should work as expected.

**Comment by rapcmia** [comment] 2022-12-21 06:20
Hi @Albonida good day,
The foundation team had some changes related to tokenListSource on our upcoming release version 1.11.0. We would like you to possibly check it and should address a fix for this issue. The latest patch enables users to edit the json file so its easier to add tokens which are not part of the default list. Thank you 🙇

**Closed** 2022-12-21 06:22 UTC
Labels: bug, arbitrum_one
