### ISSUE TITLE
Client - Total allocated balance exceeds 100%

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4946] opened 2021-12-20 06:46 UTC
**Describe the bug**
When running the balance command with all assets currently used the total allocated % exceeds 100.00%.

**Steps To Reproduce**
1. Run any supported strategy that can place orders
2. Set the order amount to be able to place all your available asset
3. Run balance command

**Screenshots**
<img width="908" alt="Screen Shot 2021-12-20 at 2 37 02 PM" src="https://user-images.githubusercontent.com/64377055/146723313-211be625-f6f2-4bd7-93de-871135d9ae56.png">

<img width="919" alt="Screen Shot 2021-12-20 at 2 36 22 PM" src="https://user-images.githubusercontent.com/64377055/146723308-36365ceb-6cdd-4322-9e52-ba19a261c293.png">

**Release version**
development-1.0.0

**Comment by sisco0** [comment] 2021-12-25 19:27
The referred source code line is shown next:
https://github.com/hummingbot/hummingbot/blob/cb3ee5a30a2feb0a55ceca9d200c59662d7e3057/hummingbot/client/command/balance_command.py#L114

The issue is probably because of this other _smart rounding_ procedure for the summed column:
https://github.com/hummingbot/hummingbot/blob/cb3ee5a30a2feb0a55ceca9d200c59662d7e3057/hummingbot/client/command/balance_command.py#L161

You should ensure that this error is gone by using a hidden column without rounding.

**Comment by rapcmia** [comment] 2022-03-01 06:11
Fixed on Hummingbot version 1.1.0

**Closed by rapcmia** 2022-03-01 06:11 UTC
Labels: bug
