### ISSUE TITLE
error fetching account updates from Gate.io perpetual

### ISSUE THREAD

**Issue by HESSEBO** [hummingbot/hummingbot#6232] opened 2023-04-15 14:54 UTC
**Operating environment: linux, Docker-compose
When I run Start command I get error message showing that Hummingbot is unable to fetch account update, as a result when orders are created they get filled up but with no exit, which put me in open position until I close them manually. 

The following logs can clarify the problem that I am facing;**

2023-04-12 02:15:49,035 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2023-04-12 02:15:50,362 - 1 - hummingbot.connector.derivative.gate_io_perpetual.gate_io_perpetual_derivative.GateIoPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2023-04-12 02:15:50,982 - 1 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for BTC-USDT. 1/1 completed.
2023-04-12 02:15:51,353 - 1 - hummingbot.connector.derivative.gate_io_perpetual.gate_io_perpetual_derivative.GateIoPerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 771, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 299, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/derivative/gate_io_perpetual/gate_io_perpetual_derivative.py", line 678, in _update_positions
    hb_trading_pair = await self.trading_pair_associated_to_exchange_symbol(ex_trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'STEP_USDT'

**Comment by nikspz** [comment] 2023-04-19 11:50
Hi @HESSEBO Can't reproduce your issue (Unexpected error while fetching account updates.) 
Could you please add:

Steps to reproduce:
1
2
3

Actual bot behavior

log and config file/screenshot

Screenshot of the issue

thanks

**Comment by nikspz** [comment] 2023-05-02 06:24
Closing since no updates from user

**Closed by nikspz** 2023-05-02 06:24 UTC
Labels: bug, gate_io_perpetual
