### ISSUE TITLE
Client - Bottom nav display not always updating

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4712] opened 2021-11-15 03:30 UTC
**Describe the bug**
It has been observed that when running a bot long term with executed trades , the bottom nav starts to not update at all, even when there are new trades that are produced. This is confirmed to be happening on FTX, Huobi, Binance and Crypto.com. The first 3 hours that I ran the bots the bottom nav bar is still updating however when I checked the next day that's when the issue appeared. Creating a ticket for tracking and will update the ticket if found to be happening on other connectors as well.

**Screenshots**
<img width="1423" alt="Screen Shot 2021-11-15 at 10 41 37 AM" src="https://user-images.githubusercontent.com/64377055/141717419-52341ce5-328f-4e10-a03f-cde0678fc1d4.png">

**Release version**
development-0.46.0

**Comment by dennisocana** [comment] 2021-11-15 03:51
This also happens while running on Kucoin and AscendEX.

**Comment by petioptrv** [comment] 2021-12-08 03:38
@rxlxrxsx (@CoinAlpha/qa-team), I've added several debug statements around the area of concern to try and pin-point the source of the issue. Please run a test from [this branch](https://github.com/CoinAlpha/hummingbot/tree/fix/trade_monitor_freezing) and post the logs here once the issue appears again. The branch is identical to `development` with the extra debugging log statements.

Also, please notice if the right-side panel is frozen as well (CPU and memory usages).

Finally, it's possible that this is due to some logic being executed at the start of the subsequent day. To test this hypothesis, either leave the bot running for more than a day (as in the initial report), or change the computer system time zone to something that will result in a change of date soon... Unless, @rxlxrxsx, you can confirm that the second order was placed in the same date as the first one (meaning that the panel failed to update within the same day), in which case we can disregard this possibility entirely.

**Comment by rapcmia** [comment] 2021-12-13 13:49
Hi @petioptrv, my testbot for Binance was able to reproduce the issue. Please see attached for the config and log files requested. Thank you

![Screenshot 2021-12-13 213920](https://user-images.githubusercontent.com/73840223/145823833-c75c615a-d416-4c2b-ad9c-b5e9101d1816.png)

Attached:
[trade_monitor_freezing.zip](https://github.com/CoinAlpha/hummingbot/files/7704279/trade_monitor_freezing.zip)

**Comment by genecheon** [comment] 2022-01-18 05:42
Fixed by https://github.com/hummingbot/hummingbot/pull/4923

**Closed by genecheon** 2022-01-18 05:42 UTC
Labels: P1, bug
