### ISSUE TITLE
永续合约"Not enough budget to open position"BUG

### ISSUE THREAD

**Issue by phpmac** [hummingbot/hummingbot#6839] opened 2024-02-07 15:04 UTC
### Describe the bug

`hummingbot/smart_components/executors/position_executor/position_executor.py`

```py

   adjusted_order_candidate = self.adjust_order_candidate(order_candidate)
        if not adjusted_order_candidate:
            self.terminate_control_loop()
            self.close_type = CloseType.INSUFFICIENT_BALANCE
            self.executor_status = PositionExecutorStatus.COMPLETED
            error = "Not enough budget to open position."
            self.logger().error(error)

    def adjust_order_candidate(self, order_candidate):
        adjusted_order_candidate: OrderCandidate = self.connectors[self.exchange].budget_checker.adjust_candidate(order_candidate)
        if adjusted_order_candidate.amount > Decimal("0"):
            return adjusted_order_candidate



```

需要加入合约杠杆，比如本金只有400usdt，10x杠杆，无法开仓500美金，程序没有计算好，会导致提示Not enough budget to open position
<img width="648" alt="截屏2024-02-07 23 04 29" src="https://github.com/hummingbot/hummingbot/assets/86544347/3435572a-a2db-4d47-bd3b-1a0b361dca2e">

### Steps to reproduce

`hummingbot/smart_components/executors/position_executor/position_executor.py`

```py

   adjusted_order_candidate = self.adjust_order_candidate(order_candidate)
        if not adjusted_order_candidate:
            self.terminate_control_loop()
            self.close_type = CloseType.INSUFFICIENT_BALANCE
            self.executor_status = PositionExecutorStatus.COMPLETED
            error = "Not enough budget to open position."
            self.logger().error(error)

    def adjust_order_candidate(self, order_candidate):
        adjusted_order_candidate: OrderCandidate = self.connectors[self.exchange].budget_checker.adjust_candidate(order_candidate)
        if adjusted_order_candidate.amount > Decimal("0"):
            return adjusted_order_candidate



```

需要加入合约杠杆，比如本金只有400usdt，10x杠杆，无法开仓500美金，程序没有计算好，会导致提示Not enough budget to open position
<img width="648" alt="截屏2024-02-07 23 04 29" src="https://github.com/hummingbot/hummingbot/assets/86544347/3435572a-a2db-4d47-bd3b-1a0b361dca2e">

### Release version

latest

### Type of installation

Source

**Comment by nikspz** [comment] 2024-02-14 06:37
Closing issue since no steps to reproduce added

**Closed by nikspz** 2024-02-14 06:37 UTC
Labels: bug
