### ISSUE TITLE
Orders Stay Alive Past Time Limit on GateIO

### ISSUE THREAD

**Issue by sissnad** [hummingbot/hummingbot#7133] opened 2024-07-22 11:15 UTC
### Describe the bug

I run  `pmm_dynamic` on gate-io TLOS-USDT. I set the `time-limit` to 60 seconds. At some point the bot fails to cancel individual orders, and they stay alive past the time-limit. The corresponding executors seem to be terminated though.
<img width="1487" alt="Screenshot 2024-07-22 at 12 55 27" src="https://github.com/user-attachments/assets/41f56adf-c6bd-4a68-bf20-25ad05accf6d">

### Steps to reproduce

1. Spin up HB docker v2.0.0.
2. Create script-config with `pmm_dynamic_config.yml`  for GateIO TLOS-USDT and start it.
3. Wait 1-2 hrs.

### Release version

2.0.0

### Type of installation

Docker

### Attach required files

[config.zip](https://github.com/user-attachments/files/16332058/config.zip)
[logs.zip](https://github.com/user-attachments/files/16332061/logs.zip)

**Comment by Jbekker** [comment] 2024-07-22 18:38
If I follow t-HBOTBTSUT61dd35279072e7504e5 through the logs, it looks like it's trying to close the order. I see a market buy order:
`2024-07-22 10:15:19,467 - 15 - hummingbot.connector.client_order_tracker - INFO - Created MARKET BUY order t-HBOTBTSUT61dd35279072e7504e5 for 29.06 TLOS-USDT.`
That is being filled:
`2024-07-22 10:15:19,493 - 15 - hummingbot.connector.client_order_tracker - INFO - The BUY order t-HBOTBTSUT61dd35279072e7504e5 amounting to 29.05/29.06 TLOS has been filled`
But then the order that is already filled is getting canceled:
`2024-07-22 10:15:20,258 - 15 - hummingbot.strategy.script_strategy_base - INFO - (TLOS-USDT) Canceling the limit order t-HBOTBTSUT61dd35279072e7504e5. [clock=2024-07-22 10:15:20+00:00]`
Which then fails because it doesn't exist:
`OSError: Error executing request DELETE https://api.gateio.ws/api/v4/spot/orders/638268045472. HTTP status is 404. Error: {"label":"ORDER_NOT_FOUND","message":"Order not found"}`

Soo interesting events, my guess is that the order status is not correctly updated.

**Comment by nikspz** [comment] 2024-07-23 05:19
checking this ticket

**Comment by nikspz** [comment] 2024-07-23 08:23
Upon checking can't reproduce this behavior on cloud server + docker installation

[gate1.zip](https://github.com/user-attachments/files/16345753/gate1.zip)
[logs_gate111.log](https://github.com/user-attachments/files/16345692/logs_gate111.log)
![image](https://github.com/user-attachments/assets/4bd6cdfa-d8b4-453f-81e6-68c1799859b9)
![image](https://github.com/user-attachments/assets/24e76a94-a369-4018-9e5f-8a0c94bb5e7c)




> ### Describe the bug
>  `pmm_dynamic` on gate-io TLOS-USDT. I set the `time-limit` to 60 seconds. At some point the bot fails to cancel individual orders, and they stay alive past the time-limit. The corresponding executors seem to be terminated though. 

I think reason could be time-limit (time before placing MARKET order to CLOSE position) 60 is could be low and since stop-loss is tight as well.
Also from logs looks like Unexpected error while retrieving rates from Binance.  (Service unavailable from a restricted location) so maybe reasonable to change rate oracle source to gate io / other
https://hummingbot.org/strategy-configs/rate-oracle/

**Comment by sissnad** [comment] 2024-07-23 09:50
For me it takes 1-2hrs for the issue to appear. I guess you had the bot running for some time

**Comment by sissnad** [comment] 2024-07-23 09:54
> I think reason could be time-limit (time before placing MARKET order to CLOSE position) 60 is could be low and since stop-loss is tight as well.

🤔 short time-limit and / or stop-loss is something that at least for some of my setups is requirement. If `Triple Barrier` indeed has these constraints, I need to find a modification that works for me.

**Comment by nikspz** [comment] 2024-07-23 10:28
> short time-limit and / or stop-loss is something that at least for some of my setups is required. 

Okay, I'll try to check with exact config later

**Comment by nikspz** [comment] 2024-07-24 11:35
https://github.com/hummingbot/hummingbot/pull/7134

**Comment by nikspz** [comment] 2024-10-24 15:07
Closing this issue, fix merged to development branch, will be available in 2.0.2 release

**Closed by nikspz** 2024-10-24 15:07 UTC
Labels: bug, gate_io
