### ISSUE TITLE
Issue with Gate.io balance

### ISSUE THREAD

**Issue by glarkou** [hummingbot/hummingbot#5871] opened 2022-11-08 16:25 UTC
**Describe the bug**
The available balance on Gate.io is wrong and the bots tries to open trades with greater than the actual available balance.

**Steps To Reproduce**
Just start the bot with xemm and after a while you ll observe that the `Total` balance becomes less than the `Available` balance.

I usually observed this yes I have balance to buy and sell.
...

**Screenshots**
![image](https://user-images.githubusercontent.com/25099792/200620072-62e88ce2-64c5-4c98-b4a2-c0d69ca6a918.png)

How can the total balance be less than the available balance

**Release version**
version 1.9.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment] 2022-11-16 06:55
Hi @glarkou good day to you
Thanks for reporting this issue, I am able to reproduce it by monitoring a the total and available balance while running the client on `status --live` which we have reported that there seems to be delay under https://github.com/hummingbot/hummingbot/issues/5756. You would notice this after few trades and should be updated at the event of recreating orders again in which can be reproduce on PMM's order_refresh_time or `filled_order_delay`

We suggest to add yours as a comment on the ticket so we can close this as a duplicate. Thank you!

**Comment by glarkou** [comment] 2022-11-17 13:05
@rapcmia but are you sure that these two issues are related?

Because the other one describes the issue where you might submit an order and haven't got a notification that is was canceled resulted into double the balance. This one, I think it's a bit more random, complicated since the issue might be open for a longer period of time.

**Comment by nikspz** [comment] 2022-11-18 04:31
hi @glarkou, yep, the issue you mentioned (`total balance be less than the available balance`) is related to ongoing issue https://github.com/hummingbot/hummingbot/issues/5756 (Gate.io - Delay updating Total balance #5756). That's a known issue and team aware of it.

**Comment by nikspz** [comment] 2022-11-21 23:17
Closed that issue as duplicated with #5756

**Closed by nikspz** 2022-11-21 23:17 UTC
Labels: bug, gate_io
