### ISSUE TITLE
Binance perpetual - Unexpected error updating funding info.

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6653] opened 2023-11-13 12:25 UTC
### Describe the bug

When reviewing long term bots, there are instances of `Unexpected error updating funding info.` when placing orders. The timestamps and type of order placed is random but the connector still able to create the order successfully

```
2023-11-08 12:26:26,394 - 14 - hummingbot.connector.perpetual_trading.PerpetualTrading - ERROR - Unexpected error updating funding info.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_trading.py", line 175, in _funding_info_updater
    funding_info = self._funding_info[trading_pair]
KeyError: 'BAKE-USDT'
```

### Steps to reproduce

1.  Setup a strategy or script using binance perpetuals 
2. Setup with spreads enough to open/close position
3. Run for couple of hours or overnight
4. Review log file

### Release version

dev-1.22

### Type of installation

Source

### Attach required files

[logs_binperp_market-making_dman_v3_multiple_pairs_arit.log](https://github.com/hummingbot/hummingbot/files/13334752/logs_binperp_market-making_dman_v3_multiple_pairs_arit.log)

**Comment by nikspz** [comment] 2024-01-19 12:42
Upon checking on longterm run, issue not reproduced
Closing this since payment has been sent.

**Closed by nikspz** 2024-01-19 12:42 UTC
Labels: P3, bug, binance_perpetual
