### ISSUE TITLE
Kraken: kraken_api_order_book_data_source - Unexpected error

### ISSUE THREAD

**Issue by dscreet** [hummingbot/hummingbot#5551] opened 2022-07-31 10:59 UTC
**Describe the bug**
After creating a PMM strategy, connecting to Kraken and starting the bot, I get an error 'listening to order book streams'. I have tried this with all possible XLM-XXX pairs supported on Kraken and the error is consistent.

**Steps To Reproduce**
1. Set up your configuration file with these parameters: PMM, Kraken (Intermediate), XLM-BTC.
2. Start the bot using this command: "start" and make sure all preliminary checks are successful.
3. You will start seeing the recurring error in the log pane within the minute.

**Screenshots**
![image](https://user-images.githubusercontent.com/29370740/182022640-14620287-1475-4a37-b61e-6490baf44ec6.png)

**Release version**
1.6.0

**Attachments**
Log file: [https://ctxt.io/2/AADglx4hFg](url)

**Comment by dscreet** [comment] 2022-07-31 11:15
Update: I have also tried using avellaneda_market_making, same error.

**Comment by dscreet** [comment] 2022-07-31 11:24
Update: I have tried the same setup on Hummingbot Test Drive, same error.

**Comment by dscreet** [comment] 2022-07-31 11:58
My order_amount was 5 for XLM and it seems that the min is 10 for Kraken https://support.kraken.com/hc/en-us/articles/205893708-Minimum-order-size-volume-for-trading.

I am now able to trade, however, I'm still getting the same error message.

**Comment by AnchApp** [comment] 2022-09-05 12:53
Same issues with other strategy

**Comment by MementoRC** [comment] 2022-09-08 21:11
Confirmed the issue, there seems to be a quick work-around for this. The full correction requires a re-factoring of the connector to updated standard (like binance connector) - I will still propose the quick-turn and we'll see if it is accepted

**Comment by MementoRC** [comment] 2022-09-08 23:39
Could you try adding to`kraken_api_order_book_data_source.py`:
```    async def listen_for_subscriptions(self):
        """
        Connects to the trade events and order diffs websocket endpoints and listens to the messages sent by the
        exchange. Each message is stored in its own queue.
        """
        # New method not yet implemented in this connector
        pass
```
This worked for me

**Comment by preze93** [comment] 2022-10-11 11:03
@MementoRC was this issue already merged? I'm still getting this error on HBOT

**Comment by MementoRC** [comment] 2022-10-11 16:08
@preze93 Not yet, it is still opened. I think the team priority is on the Certified Exchanges. You could attempt a source install, implement the change (simply adding a few lines - see the changes) and re-build the docker image

**Comment by jskrivanek** [comment] 2022-11-16 21:04
> You could attempt a source install, implement the change (simply adding a few lines) and re-build the docker image

@MementoRC Could you please provide some details here?

**Comment by rapcmia** [comment] 2024-04-02 13:36
As of release version 1.26.0, `kraken` has been updated to latest connector standard

**Closed by rapcmia** 2024-04-02 13:36 UTC
Labels: bug, kraken
