### ISSUE TITLE
Client - Cannot set `gateway.gateway_api_host` via config command

### ISSUE THREAD

**Issue by klpanagi** [hummingbot/hummingbot#6076] opened 2023-02-12 21:01 UTC
**Describe the bug**
Cannot set gateway host via config command.
Seems like the `gateway.gateway_api_host` parameter is not listed in configurable parameters in client source code.

**Steps To Reproduce**
Here are the steps to reproduce the issue:

1. Start a hummingbot instance.
2. Execute `config` + `<TAB> ` for completion to pop
3. Observe that the `gateway.gateway_api_host` is not listed

Even if you execute `config gateway.gateway_api_host` command will result in error

**Screenshots**

![2023-02-12-225511_756x95_scrot](https://user-images.githubusercontent.com/4770702/218336849-428a74b6-03a2-44bf-9ad4-a7fb0723a98a.png)

**Release version**
1.12.0

**Discord username:** klpanagi

**Comment by nikspz** [comment] 2023-02-13 07:58
hi @klpanagi, upon crosschecking with qa
couldn't reproduce the issue on 1.12.0 and dev-1.13.0
![6076 issue gateway port](https://user-images.githubusercontent.com/83953535/218401288-337aed9f-3225-4111-b7e1-d7c59c8816ff.gif)
development:
![6076 issue gateway port dev](https://user-images.githubusercontent.com/83953535/218401857-8cbda817-ff16-41ed-9234-251ea0501fd1.gif)

**Comment by nikspz** [comment] 2023-02-13 08:03
What about `gateway.gateway_api_host` - yes, currently 
can't change using `config gateway.gateway_api_host` returns invalid key warning message

![image](https://user-images.githubusercontent.com/83953535/218402792-333f31cc-64ca-4a5b-a120-48fcfa03f1b9.png)

**Comment by klpanagi** [comment] 2023-02-14 18:05
Yes, I was referring to the `gateway_api_host` parameter.
I dont know if it has been removed from configurable parameters in the later PRs, but it is really useful to be able to config the host for the gateway, especially now that the gateway source was moved to another repository and people can deploy in virtualized environments (networks in compose, clusters etc).

**Comment by cardosofede** [comment] 2023-02-20 20:17
@klpanagi it should be possible to change that, do you want to create the PR? it should be simple

**Comment by cardosofede** [comment] 2023-02-20 20:17
@klpanagi it should be possible to change that, you can nominate this issue to the poll of March, and I will vote in favor

**Comment by klpanagi** [comment] 2023-02-22 19:17
> @klpanagi it should be possible to change that, you can nominate this issue to the poll of March, and I will vote in favor

Thanks @cardosofede , will nominate this to the poll.

**Comment by nikspz** [comment] 2023-03-10 06:26
This issue is assigned to HB Foundation team

**Comment by fengtality** [comment] 2023-03-15 19:31
I have scoped the issue and believe it's a P3 bounty, which is currently 10,000 HBOT (https://docs.hummingbot.org/governance/bounties/#bug-bounty-schedule).

@klpanagi Thanks for your interest in working on it - I will assign the bounty to you - please submit a PR to `development` and we will merge it in.

**Comment by klpanagi** [comment] 2023-03-21 17:31
Thank you @fengtality .

**Comment by klpanagi** [comment] 2023-03-22 17:39
@fengtality  I have created the PR that resolves this issue

https://github.com/hummingbot/hummingbot/pull/6159

**Comment by fengtality** [comment] 2023-03-23 16:37
#6159 has been approved and merged to `development` branch. @carlitogetaladajr please arrange for payment of 10,000 HBOT to @klpanagi's ETH wallet address on file. Thanks for your contribution to Hummingbot!

**Closed by fengtality** 2023-03-23 16:37 UTC
Labels: bug
