### ISSUE TITLE
XEMM rate oracle not working with different quotes assets and base assets

### ISSUE THREAD

**Issue by jellebuth** [hummingbot/hummingbot#5068] opened 2022-01-28 11:40 UTC
**Describe the bug**
The bot is only placing sell orders when using cross exchange market making with two different base pairs. Also it cancels the order right away with the message: "order size limit is now less than the active order amount (amount), going to adjust the order". 

I think there is a problem in the calculations of the available balances or the use of the oracle.

i also want to mention that the rate oracle does not work when having two different base assets.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Run the bot on kucoin SHR-BTC (maker) SHR-USDT taker with a min profitability of 0.6 and the rest basic settings. 

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
![image](https://user-images.githubusercontent.com/83583507/151540810-0ec0d562-a832-4a1a-85e1-18e52168ffac.png)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by nikspz** [comment] 2022-03-24 11:26
We Need to refactor XEMM Logic for different base assets and different quote assets.
![image](https://user-images.githubusercontent.com/83953535/159906034-7cfe21f0-2311-47ac-a00d-0fbec781e01b.png)
Actual: 
No changes in config after bot ask user of rate of the token
Bot using price of one base asset for another base asset orders

Expected:
Bot change conversion rates accordingly to rate oracle source
Each asset placed with correct price

**Comment by nikspz** [comment] 2022-09-28 19:01
Reproduced on dev-1.8.0

**Comment by nikspz** [comment] 2022-09-30 15:01
![image](https://user-images.githubusercontent.com/83953535/193298432-85747a94-ccb5-4cf2-b489-2220ae2ac5dd.png)
Steps to reproduce:
Create a XEMM strategy using different pairs (BTC-USDT and ETH-USDT)
Set up `conversion_rate_mode` to `rate_oracle_conversion_rate`
Start the bot and look at the log pane 

Actual:
Bot using price of one base asset when create another base asset orders (Uses ETH price for BTC)

**Comment by rapcmia** [comment] 2022-10-07 11:49
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Cross-exchange market making component

**Comment by kadirc** [comment] 2022-10-09 17:10
![image](https://user-images.githubusercontent.com/105316681/194768856-f6c1674e-8e97-4e89-a471-4e5cbe0d3720.png)

The problem is that strategy starts before the rate oracle is available, and if the rate oracle is not available, 1.0 is used as the conversion rate.

For example in @nikspz 's screenshot; since rate oracle is not available, taker to maker base conversion (ETH-BTC) rate is taken as 1.0 and and quote_conversion_rate is also 1.0 as the quote assets are the same. Which results in BTC-USDT price in maker market being equal to ETH-USDT price in taker market ( 1358$ ) for the bid order.

The ask order seem to be placed around a more sane price (instead of selling BTC @1538$ !), I guess because of price filter.

I think it would be better to wait for the rate oracle to become available if it is needed instead of using 1.0 by default.

**Comment by MementoRC** [comment] 2022-10-10 17:32
@kadirc I amended this PR:https://github.com/hummingbot/hummingbot/pull/5728 to encompass your proposal above

**Comment by kadirc** [comment] 2022-10-10 19:17
> @kadirc I amended this PR:#5728 to encompass your proposal above

@MementoRC thanks, I left a review on the PR.

**Comment by MementoRC** [comment] 2022-10-10 20:19
@kadirc, Thanks ... and cool, I am not using XEMM myself and did not know you had a new proposal. I would rather step off and let you define the solution you think works best for the users.
Will you make a PR? What do you think about the other "issues" that I thought were present?

**Comment by JeremyKono** [comment] 2022-10-26 06:40
Hi @MementoRC, this is to confirm if what PR are we supposed to look at? Yours or @kadirc PR. Thanks

**Comment by kadirc** [comment] 2022-10-26 19:45
> @kadirc, Thanks ... and cool, I am not using XEMM myself and did not know you had a new proposal. I would rather step off and let you define the solution you think works best for the users. Will you make a PR? What do you think about the other "issues" that I thought were present?

@MementoRC, another problem is that order amount and price is miscalculated with different quote or base assets, either for bid or ask orders. I don't think #5728 addresses that.

About the rate oracle, I think it is better to make sure conversion rates available rather than rate oracle, because;
- If fixed conversion rates mode is configured, why wait for rate oracle
- rate oracle might be available, but still there might be no conversion rate for a pair

I created #5812 to address both, any review is appreciated.

**Comment by MementoRC** [comment] 2022-10-26 21:30
It looks good. Federico and Nick reviews will be much more in-depth and relevant - The other PR has been closed
@JeremyKono @rapcmia FYI on a new assignee for this bounty

**Comment by MementoRC** [comment] 2022-11-02 18:02
@JeremyKono Note that this should also relate to Bounty: [XEMM - Incorrect rate oracle conversion#5695](https://github.com/hummingbot/hummingbot/issues/5695)

**Comment by JeremyKono** [comment] 2022-11-04 03:12
Hi @kadirc, can you please provide us with your ETH wallet to send the rewards? Thank you

**Comment by kadirc** [comment] 2022-11-06 22:13
> Hi @kadirc, can you please provide us with your ETH wallet to send the rewards? Thank you

Hi @JeremyKono, here it is: 0x76c8A2AD994065512a37E4B0aC8d808332704494

**Comment by JeremyKono** [comment] 2022-11-16 02:03
Bounty has been paid. Thank you for your contribution!

**Comment by nikspz** [comment] 2022-11-16 04:25
fix has been deployed https://github.com/hummingbot/hummingbot/pull/5812  and will be available on the upcoming Hummingbot version 1.10.0 release

**Closed by nikspz** 2022-11-16 04:25 UTC
Labels: P2, bug, kucoin, cross_exchange_market_making
