### ISSUE TITLE
Okx exchange GET trade fills

### ISSUE THREAD

**Issue by huatahhhhh** [hummingbot/hummingbot#5800] opened 2022-10-13 04:31 UTC
**Describe the bug**

I was running a xemm strategy with 2 trading pairs on okx exchange and noticed order fills not being updated. When my maker trades got filled, it was not being updated in the order tracker and hence no taker orders being submitted. This led to an accumulation of maker trades without any hedging on the taker side. Which led to a skew in my inventory and failure of strategy execution. 

Upon investigating the logs, I realised that the UserStream websocket was disconnected multiple times occasionally and API request to update order status constantly failed. I was only able to discover the error when adding logging statements to `ExchangePyBase._api_request` in connector/exchange_py_base.py. Here are the technical issues: 

Issues:
1. When okx exchange object calls `_request_order_fills` to GET `api/v5/trade/fills`, it is constantly receiving a 401 response `Error: {"msg":"Invalid Sign","code":"50113"}`

2. When `ExchangePyBase._api_request()` fails even after 2 retries, no error message is found in logs

**Steps To Reproduce**
1. Go to connector/exchange_py_base.py (here) and add 2 logging statements for both successful and failed api requests (see screenshot)
2. Start the bot and run a strategy using okx exchange (I used cross exchange market making)
3. Let the strategy run for a while
4. Check the logs by `grep -RI 'trade/fills' <logfile>`, this shows that all calls to `api/v5/trade/fills` fails

**Screenshots**
Log statements:
![Screenshot from 2022-10-13 12-17-24](https://user-images.githubusercontent.com/56010790/195500481-870a0e48-d683-4a40-bda4-df80cd0882e4.png)

Error logs: 
![Screenshot from 2022-10-13 12-22-14](https://user-images.githubusercontent.com/56010790/195500825-888413ce-d2e1-4a41-bc45-65f5773ec9ce.png)

**Release version**
v1.8.0

**Optional: your discord username:**
huatahhhh#5633

**Comment by nikspz** [comment] 2022-10-13 09:04
Hi @huatahhhhh Could you please tell your machinetype (AWS/local) OS and installation type (Source/Docker)?
 Could you please also send your config and log files? it could help a lot to triage the issue.
 
 I tried to reproduce using AVAX-USDT Pair, but can't reproduce the issue
![image](https://user-images.githubusercontent.com/83953535/195552772-c947cece-231f-4532-8884-5476da7afd9d.png)

**Comment by huatahhhhh** [comment] 2022-10-14 15:30
@nikspz Do follow the steps to reproduce and add the logging statements in the code.

**Comment by huatahhhhh** [comment] 2022-10-25 16:47
@nikspz API calls for `api/v5/trade/fills` is crafting the digital signature wrongly. This leads to hummingbot order tracker not capturing trade fills when web socket is disconnected as well as triggering the throttle limit (when a api call fails, hummingbot will reattempt synchronising of clock).

Please follow my above steps - adding logging lines to source code to verify the issue. I would like apply to fix this and potentially get the bounty :)
 
![Screenshot from 2022-10-26 00-39-10](https://user-images.githubusercontent.com/56010790/197832756-934f601a-5325-49f3-be98-8afe1b088fb2.png)

**Comment by nikspz** [comment] 2022-10-25 18:25
Severity: P3
Bounty: 10000 (https://hummingbot.org/maintenance/bugs/)
Rationale:  Bug related to OKX, certified connector

**Comment by nikspz** [comment] 2022-10-25 18:33
Assigning this issue to @huatahhhhh . Thank you for your contribution!

**Comment by huatahhhhh** [comment] 2022-10-26 01:52
thank you @nikspz

**Comment by huatahhhhh** [comment] 2022-10-28 05:19
@JeremyKono The PR is not for this issue. I will be submitting a PR for this soon

**Comment by huatahhhhh** [comment] 2022-11-01 17:55
@JeremyKono  please unlink this issue from PR #5828

**Comment by JeremyKono** [comment] 2022-12-05 11:33
Hi @huatahhhhh do you have any updates on this issue?

**Comment by huatahhhhh** [comment] 2022-12-05 11:44
@JeremyKono I have submitted a PR for this issue #5900 . Awaiting for someone on the team to review the code

**Comment by nikspz** [comment] 2023-05-12 09:12
Issue was fixed in #5900 
@huatahhhhh please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by nikspz** [comment] 2023-05-22 05:21
Closing this bounty as paid

**Closed by nikspz** 2023-05-22 05:21 UTC
Labels: P3, bug, cross_exchange_market_making, bounty, okx
