### ISSUE TITLE
Can't add new paper trading spot connectors using Avellaneda market making strategy

### ISSUE THREAD

**Issue by aagoldberg** [hummingbot/hummingbot#5954] opened 2022-12-15 16:23 UTC
**Describe the bug**
When I add new paper trading spot connectors to the conf_client.yml, they work with the pure_market_making script but not the avellaneda_market_making script. 

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Add a new exchange to the conf_client.yml paper_trade_exchanges list, such as 'mexc'.
2. Start the bot, either from source on through docker
3. Create a new strategy using the 'avellaneda_market_making' strategy
4. Choose a paper trading spot connector associated with the exchange above, such as 'mexc_paper_trade'
...

**Screenshots**
Working with pure_market_making strategy:
![image](https://user-images.githubusercontent.com/10750984/207912754-f93c5381-0062-46c7-9bf1-0d2cda5f7e52.png)
Rejected by avellaneda_market_making strategy:
![image](https://user-images.githubusercontent.com/10750984/207912640-c135be4b-d564-47a9-b6b3-6e2087c88f18.png)

**Release version**
1.10 (docker)

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by aagoldberg** [comment] 2022-12-15 18:17
It does work if you:
1. Add the connector, ie 'mexc_paper_trade' to PAPER_TRADE_EXCHANGES in hummingbot.client.settings.py
2. Add the exchange, ie 'mexc' to conf_client.yml
3. Recompile (./compile)

However, the documentation only suggests number 2 (conf_client.yml) is needed.

**Comment by fengtality** [comment] 2022-12-20 20:57
@rapcmia @nikspz please test this and let @JeremyKono @david-hummingbot know if docs changes are needed

**Comment by rapcmia** [comment] 2022-12-21 06:02
HI @aagoldberg good day to you
I can confirm that adding other exchanges like mexc as paper_trade connector works for steps 1 and 2. I think there's no need to recompile unless you want to compile it again to make sure 👍 

> It does work if you:
> 
> 1. Add the connector, ie 'mexc_paper_trade' to PAPER_TRADE_EXCHANGES in hummingbot.client.settings.py
> 2. Add the exchange, ie 'mexc' to conf_client.yml
> 3. Recompile (./compile)

**Comment by rapcmia** [comment] 2023-01-05 05:55
Closing ticket for now since the workaround provided. Informed the team about updating the papertrade connector on docs 🙇

**Closed by rapcmia** 2023-01-05 05:55 UTC
Labels: bug, avellaneda_market_making
