### ISSUE TITLE
KuCoin - Unexpected error while fetching trading fees

### ISSUE THREAD

**Issue by PhatJay76** [hummingbot/hummingbot#5545] opened 2022-07-28 17:57 UTC
Version 1.6.0 

Kucoin connector 
Liquidity Mining Stragety 

markets: DAO-USDT,XCAD-USDT,AVAX-USDT,FRONT-USDT,HOTCROSS-USDT,ALGO-USDT,ONE-USDT,SHR-USDT,ETH-USDT,FEAR-USDT,ODDZ-USDT,NIM-USDT

2022-07-28 17:47:54,442 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Could not fetch new trading fees from Kucoin. Check network connection.
2022-07-28 17:47:55,130 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - NETWORK - Unexpected error while fetching trading fees.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 713, in _trading_fees_polling_loop
    await safe_gather(self._update_trading_fees())
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 341, in _update_trading_fees
    fees_json = resp["data"]
KeyError: 'data'

This spams the logs/console very frequently and I suspect it is leading to a memory leak/crash [cannot prove it]

Discord User: PhatJay#4958

**Comment by ethicrypt** [comment] 2022-08-24 18:12
I would like to be assigned this bounty. I have been spending a lot of time in the code for the KuCoin connector as well as the liquidity mining strategy so this would be a good fit for me. This would be my first official Hummingbot development work, but I'm a professional software engineer with over 5 years of experience.

**Comment by JeremyKono** [comment] 2022-08-25 00:57
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to a component

**Comment by JeremyKono** [comment] 2022-08-25 00:58
Assigning this issue to @ethicrypt. Thank you for applying!

**Comment by ethicrypt** [comment] 2022-08-26 22:05
In debugging this issue, it appears that this issue is isolated to situations where there are more than 10 markets being specific in one strategy. In the KuCoin API documentation, I found the following regarding the API call to get trading fees:

"You can inquire about fee rates of 10 trading pairs each time at most."

That quote lines up with the behavior in Hummingbot, so I will explore a solution where multiple, separate trading fee calls are made if there are more than 10 markets in the strategy.

**Comment by ethicrypt** [comment] 2022-08-26 22:06
In the interim, as a workaround it would be feasible to create multiple liquidity mining strategies where no more than 10 markets are listed in each strategy.

**Comment by mifeng** [comment] 2022-08-31 01:37
Thanks for the investigation. Foundation considers this issue resolved as this seems like expected behavior per the Kucoin API docs if the user runs 10+ markets.

What is your ETH address for payment?

**Comment by mifeng** [comment] 2022-08-31 02:02
Foundation will close this issue after getting the ETH address of the assigned dev

**Comment by ethicrypt** [comment] 2022-08-31 21:09
> Thanks for the investigation. Foundation considers this issue resolved as this seems like expected behavior per the Kucoin API docs if the user runs 10+ markets.
> 
> What is your ETH address for payment?

0x493ADd425Fa94Dd93f69389e996bD847d40729cE

I did put together a code fix where it chunks the trading fee calls into groups of 10, but if the Foundation feels this should be closed as is then I won't go ahead with committing that.

**Comment by mifeng** [comment] 2022-09-02 01:12
> I did put together a code fix where it chunks the trading fee calls into groups of 10, but if the Foundation feels this should be closed as is then I won't go ahead with committing that.

Thanks - while that PR would address this issue, Hummingbot should be conservative in applying fixes to edge cases like this, so I don't think we should merge in that fix unless the community believes it's absolutely necessary.

**Closed by mifeng** 2022-09-02 01:12 UTC
Labels: P2, bug, kucoin, liquidity_mining, bounty_hbot, Low, wontfix

**Comment by leastchaos** [comment] 2022-09-03 05:43
I think it may be beneficial to merge the fix since the fix has been made. There are use cases, even now, where there is a need to set multiple markets in the strategy. E.g, liquidity mining allows for multiple markets, and hedge strategy also can add multiple markets, so both strategies would be limited in the number of markets added because of this issue. There are also other strategies that could be created such as the basket trading strategy which could be limited by this issue.

**Comment by mifeng** [comment] 2022-09-06 23:20
Agree that there is a need to set multiple markets for strategies, but this
issue seems to only affect 10+ markets loaded in a strategy. I would be
worried that adding logic to handle this edge case may cause other issues
down the road but not help that many users.
