### ISSUE TITLE
Binance perpetual - Unexpected error while fetching last fee payment

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6602] opened 2023-10-10 05:14 UTC
### Describe the bug

An error of `Unexpected error while fetching last fee payment` happened when the bot was creating orders to open position.

```
2023-10-09 13:30:00,042 - 14 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for LTC-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 790, in _fetch_last_fee_payment
    payment_response = await self._api_request(
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 857, in _api_request
    raise IOError(f"Error executing request {method.name} {path_url}. "
OSError: Error executing request GET /income. HTTP status is 400. Error: {
  "error" : "Internal error: 1"
}
```

This seems related to the funding_payment and only occurred once on the logs:
- There were no open position
- There were no filled orders before and after the error happened
- The connector successfully canceled and created order on each refresh cycle

_Note: Opened ticket for monitoring and looking other possible cause of error 👀_ 

### Steps to reproduce

Steps to reproduce:
1. Error found when using core strategy (perpetual market making)
2. Setup a Perp-MM strategy and run more than 24hours
3. Review log files 

### Release version

dev-1.21.0

### Type of installation

Source

### Attach required files

[logs_test_perpmm.log](https://github.com/hummingbot/hummingbot/files/12853060/logs_test_perpmm.log)
[test_perpmm.yml.log](https://github.com/hummingbot/hummingbot/files/12853063/test_perpmm.yml.log)

**Comment by cardosofede** [comment] 2023-10-30 20:23
hey @rapcmia is this the same as #6574 ?

**Comment by nikspz** [comment] 2024-01-19 12:42
Upon checking on longterm run, issue not reproduced
Closing this since payment has been sent.

**Closed by nikspz** 2024-01-19 12:42 UTC
Labels: P3, bug, binance_perpetual
