### ISSUE TITLE
Kucoin spot on Dman-v4 - Failed Sell Order Submission: KeyError in Exchange API Handling

### ISSUE THREAD

**Issue by tomasgaudino** [hummingbot/hummingbot#6764] opened 2024-01-09 21:42 UTC
### Describe the bug

I'm doing liquidity mining on XDC-USDT / Kucoin, and after some minutes I start getting from telegram an API warning:

![image](https://github.com/hummingbot/hummingbot/assets/69804854/50828fea-5a1d-4bf3-ab1f-99803ba54550)

After doing some log research, I got this traceback:

```
2024-01-09 21:00:33,680 - 16 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Failed to submit SELL order to Kucoin. Check API key and network connection.
2024-01-09 21:00:33,681 - 16 - hummingbot.strategy.script_strategy_base - INFO - Creating XDC-USDT sell order: price: NaN amount: 4067.3520.
2024-01-09 21:00:33,682 - 16 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 4067.3520 | TP Partial execution: 0
2024-01-09 21:00:33,684 - 16 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704834033.0, "order_id": "SXCUT60e899af96e2bf66f1ba71b694d55764a96", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "kucoin"}
2024-01-09 21:00:33,684 - 16 - hummingbot.connector.client_order_tracker - INFO - Order SXCUT60e899af96e2bf66f1ba71b694d55764a96 has failed. Order Update: OrderUpdate(trading_pair='XDC-USDT', update_timestamp=1704834033.0, new_state=<OrderState.FAILED: 6>, client_order_id='SXCUT60e899af96e2bf66f1ba71b694d55764a96', exchange_order_id=None, misc_updates=None)
2024-01-09 21:00:33,962 - 16 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - NETWORK - Error submitting sell MARKET order to Kucoin for 4067.3520 XDC-USDT NaN.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 217, in _place_order
    return str(exchange_order_id["data"]["orderId"]), self.current_timestamp
KeyError: 'data'
```

### Steps to reproduce

1. Build Hummingbot dev-1.24.0 image locally
2. Load the following script: https://gist.github.com/tomasgaudino/44a9ad5d57fe4ca0f56556396d4d9bae
3. Dman v4 controller has no changes from actual source code
4. Run Hummingbot with Docker
5. Start provided script on XDC-USDT and SWASH-USDT / Kucoin Spot (optional: sync a miner account)
6. Wait until API crashes

### Release version

dev-1.24.0

### Type of installation

Docker

### Attach required files

- Logs file: [logs_dman_v4_spot_2024_q1.log](https://github.com/hummingbot/hummingbot/files/13879929/logs_dman_v4_spot_2024_q1.log)

**Comment by rapcmia** [comment] 2024-01-12 03:14
- Able to reproduce the error and stuck on submitting orders to Kucoin spot connector
    ```
    2024-01-11 20:35:21,391 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - NETWORK - Error submitting sell LIMIT order to Kucoin for 352.1389 XDC-USDT 0.05141.
    Traceback (most recent call last):
      File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
        await self._place_order_and_process_update(order=order, **kwargs,)
      File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
        exchange_order_id, update_timestamp = await self._place_order(
      File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 217, in _place_order
        return str(exchange_order_id["data"]["orderId"]), self.current_timestamp
    KeyError: 'data'
    ```
    - We used the user’s attached script but only able to run single market and able to reproduce
    - The connector has been stuck trying to submit an error and returning `KeyError: 'data'` all the time 
    - See log files [here](https://drive.google.com/drive/u/0/folders/1w1iTfzzabk29y2bSj4BL7IkXUkvrb22A)

**Comment by nikspz** [comment] 2024-01-30 06:57
### Description

Research of cause of the issue and possible fix Kucoin spot on Dman-v4 - Failed Sell Order Submission 
the main issue: https://github.com/hummingbot/hummingbot/issues/6764
 
**Expected Outcome:**
The issue causing the API warning should be identified and resolved. The script should execute without triggering the API warning.

**Deliverables:**
1. Clear explanation of the root cause of the API warning.
2. Modified code to fix the issue.
3. Confirmation that the provided script executes without warnings.

**Submission Guidelines:**
Provide a pull request with the fix on the official Hummingbot repository. Include a detailed explanation of the changes made and any relevant testing results.

### Bounty

- Sponsor: Hummingbot Foundation
- Bounty amount: 50K HBOT
- Developer portion: 50K HBOT

**Comment by nikspz** [comment] 2024-02-21 19:56
Issue could be related to `not enough budget to OPEN position` for Spot connectors

Pre-conditions for your script:
1. use SPOT connector
2. set up config or modify default d-man-v4 to use TOKEN that you have 0 / low balance


[logs_dmanv4_kucoinspotrebalance.log](https://github.com/hummingbot/hummingbot/files/14364283/logs_dmanv4_kucoinspotrebalance.log)
[dmanv4_kucoinspotrebalance - Copy.txt](https://github.com/hummingbot/hummingbot/files/14364286/dmanv4_kucoinspotrebalance.-.Copy.txt)


```
2024-02-21 19:40:11,793 - 2405784 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-21 19:40:12,031 - 2405784 - hummingbot.data_feed.candles_feed.kucoin_spot_candles.kucoin_spot_candles - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-21 19:40:12,132 - 2405784 - hummingbot.data_feed.candles_feed.kucoin_spot_candles.kucoin_spot_candles - INFO - Subscribed to public klines...
2024-02-21 19:40:30,298 - 2405784 - hummingbot.strategy.script_strategy_base - INFO - Creating STRK-USDT buy order: price: 1.860527819999999998579198746 amount: 3.762373195795588805194853015.
2024-02-21 19:40:30,300 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-21 19:40:30,300 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:40:30,301 - 2405784 - hummingbot.strategy.script_strategy_base - INFO - Creating STRK-USDT buy order: price: 1.805073000000000000687561119 amount: 5.816939259520252087311980587.
2024-02-21 19:40:30,301 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-21 19:40:30,301 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:40:30,496 - 2405784 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order BSKUT611e97fd9d9487834b4ab7a0e87cd6f0557 for 3.7623 STRK-USDT.
2024-02-21 19:40:30,496 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2024-02-21 19:40:30,509 - 2405784 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1708544430.0, "type": "OrderType.LIMIT", "trading_pair": "STRK-USDT", "amount": "3.7623", "price": "1.8605", "order_id": "BSKUT611e97fd9d9487834b4ab7a0e87cd6f0557", "creation_timestamp": 1708544430.0, "exchange_order_id": "None", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "kucoin"}
2024-02-21 19:40:30,705 - 2405784 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order BSKUT611e97fd9e04d7834b4ab7a0e87cd6f0557 for 5.8169 STRK-USDT.
2024-02-21 19:40:30,705 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2024-02-21 19:40:30,715 - 2405784 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1708544430.0, "type": "OrderType.LIMIT", "trading_pair": "STRK-USDT", "amount": "5.8169", "price": "1.8050", "order_id": "BSKUT611e97fd9e04d7834b4ab7a0e87cd6f0557", "creation_timestamp": 1708544430.0, "exchange_order_id": "None", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "kucoin"}
2024-02-21 19:40:32,339 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:40:32,340 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:40:34,404 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR ----------------------------------------------
2024-02-21 19:41:25,912 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:41:27,982 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:41:27,983 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:41:30,074 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:41:30,074 - 2405784 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-02-21 19:41:31,076 - 2405784 - hummingbot.strategy.script_strategy_base - INFO - (STRK-USDT) Canceling the limit order BSKUT611e97fd9d9487834b4ab7a0e87cd6f0557. [clock=2024-02-21 19:41:31+00:00]
2024-02-21 19:41:31,175 - 2405784 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - ERROR - Failed to cancel order BSKUT611e97fd9d9487834b4ab7a0e87cd6f0557
Traceback (most recent call last):
  File "/home/nikita/sta2/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/nikita/sta2/hummingbot/connector/exchange_py_base.py", line 540, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/nikita/sta2/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 231, in _place_cancel
    if tracked_order.exchange_order_id in cancel_result["data"].get("cancelledOrderIds", []):
KeyError: 'data'
```

Bot flooded with not enough budget to OPEN position, only could solve with forced exit (exit -f)

![image](https://github.com/hummingbot/hummingbot/assets/83953535/0ebf01e4-84df-418e-bbb1-423b8a30cfba)

**Comment by cardosofede** [comment] 2024-02-23 14:03
@nikspz I already submit this fix

**Comment by rapcmia** [comment] 2024-03-08 12:19
Closing ticket, not able to reproduce issue of failed to submit order due to KeyError

**Closed by rapcmia** 2024-03-08 12:19 UTC
Labels: P2, bug, kucoin, bounty
