### ISSUE TITLE
[ERROR]  

### ISSUE THREAD

**Issue by devotedpaladin** [hummingbot/hummingbot#4861] opened 2021-12-05 07:22 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
Getting an Unexpected error running clock tick when running arbitrage strategy. This immediately happens after starting the strategy. 
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. Run a cross market making bitmart as maker and gate.io as taker
2. Notice that after starting it immediately show Unexpected error running clock tick

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/95161305/144737525-721be824-5541-45b0-a38b-c45c7e198874.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.46.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

[logs_bitmart-gate.log](https://github.com/CoinAlpha/hummingbot/files/7655404/logs_bitmart-gate.log)
*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
@Jack Black

**Comment by RC-13** [comment] 2021-12-06 03:51
Hello @devotedpaladin Are you still experiencing this issue? I tried replicating the behavior using a different maker exchange (Digifinex) instead of Bitmart however I'm unable to get the error, although I'm finding a different issue related to the display of price.
![image](https://user-images.githubusercontent.com/57189990/144784143-953178e9-76bc-4fe4-9e18-b7bda106d46b.png)
Can you share your strategy configuration?

**Comment by devotedpaladin** [comment] 2021-12-06 06:48
Hello @RC-13 yes, im still experiencing this issue,  it works fine with digifinex. problem is only bitmart as maker and gate as taker. Thanks for the reply @RC-13

**Comment by devotedpaladin** [comment] 2021-12-06 16:50
![image](https://user-images.githubusercontent.com/95161305/144887401-3c7f9b34-c747-4bf6-be0e-7882157d0fe6.png)

**Comment by RC-13** [comment] 2021-12-10 05:49
Hello, @devotedpaladin Sorry for the late response, just got our Bitmart account verified. Unfortunately, I was still unable to replicate the issue you've encountered. I don't have sufficient assets for QUACK-USDT market however as you can see, in the screenshot, the bot didn't get the error.
![image](https://user-images.githubusercontent.com/57189990/145523178-3852fe6e-0738-4771-afae-9a3b564b300b.png)
After changing the market, an order is created without the error.
![image](https://user-images.githubusercontent.com/57189990/145523532-a2ea467e-f41e-43a4-8983-a0fa639723e2.png)

What I can suggest is to try re-creating your strategy if the same issue persists or reinstall your bot.

**Comment by globeone** [comment] 2022-01-01 20:53
I get this a lot on my Kucoin bot.

From the log it says it's an SQL consistancy error.?

![image](https://user-images.githubusercontent.com/10052587/147859888-f90dab9c-40e1-4599-9b77-a31dd917f2fa.png)

here's a bit of log file

```

2022-01-01 16:51:26,505 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - ERROR - Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/home/hummingbot/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 393, in _did_complete_order
    self._update_order_status(event_tag, market, evt)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 363, in _update_order_status
    order_record: Optional[Order] = session.query(Order).filter(Order.id == order_id).one_or_none()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3316, in one_or_none
    ret = list(self)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3388, in __iter__
    self.session._autoflush()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1586, in _autoflush
    self.flush()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2571, in _flush
    flush_context.transaction = transaction = self.begin(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 947, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 316, in _begin
    self._assert_active()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 288, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: TradeFill.exchange_trade_id
[SQL: INSERT INTO "TradeFill" (config_file_path, strategy, market, symbol, base_asset, quote_asset, timestamp, order_id, trade_type, order_type, price, amount, leverage, trade_fee, exchange_trade_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]


```

**Comment by TsungWeiTsai** [comment] 2022-01-02 10:34
I am also seeing this error when using the kucoin exchange as the taker. Have you solved the issue? Thanks

**Comment by RC-13** [comment] 2022-01-10 22:31
@globeone We have a separate ticket for your concern (#4564), try deleting the current SQLite file of your strategy found on the data folder. Sometimes that issue gets fixed by having a new SQLite file.

**Comment by rapcmia** [comment] 2022-01-11 04:23
Closing ticket for now, please refer to the ticket advised on the previous comment. Thank you

**Closed by rapcmia** 2022-01-11 04:23 UTC
Labels: bug

**Comment by globeone** [comment] 2022-01-11 14:27
Deleting the SQLite file is a workaround which works but is not a solution to the root cause of the issue.
