### ISSUE TITLE
Client - Getting AttributeError when using ./start 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6947] opened 2024-04-03 06:42 UTC
### Describe the bug

There instances that when we open the client using `./start` command on CLI, we are getting `AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?`

```
(hummingbot)  ✘ ralph@hbot01  ~/github/hummingbot/6887   feat/coinbase_advanced_trade_v2.1  ./start
Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/6887/./bin/hummingbot_quickstart.py", line 32, in <module>
    from hummingbot.core.management.console import start_management_console
  File "/home/ralph/github/hummingbot/6887/hummingbot/core/management/console.py", line 10, in <module>
    import asyncssh
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/asyncssh/__init__.py", line 31, in <module>
    from .agent import SSHAgentClient, SSHAgentKeyPair, connect_agent
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/asyncssh/agent.py", line 34, in <module>
    from .public_key import KeyPairListArg, SSHCertificate, SSHKeyPair
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/asyncssh/public_key.py", line 35, in <module>
    from .crypto import ed25519_available, ed448_available
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/asyncssh/crypto/__init__.py", line 58, in <module>
    from .x509 import X509Certificate, X509Name, X509NamePattern
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/asyncssh/crypto/x509.py", line 32, in <module>
    from OpenSSL import crypto
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1579, in <module>
    class X509StoreFlags(object):
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1598, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?
```

Note: For monitoring purpose

### Steps to reproduce

TBA

### Release version

dev-1.27.0

### Type of installation

Source

**Comment by nikspz** [comment] 2024-04-11 18:10
Reproduced

![image](https://github.com/hummingbot/hummingbot/assets/83953535/9ef24513-5cb8-4beb-a7b6-e0696e18f8f3)

**Comment by nikspz** [comment] 2024-04-16 08:14
as workaround do clean reinstall with conda clean -a

```
./clean
conda deactivate
./uninstall
conda clean -a
```

Then

```
./install
conda activate hummingbot
./compile
```

**Comment by p-meier** [comment] 2024-05-03 20:41
any progress on this bug? 

Having the same issue after updating the development branch and always completely building the conda-env from fresh is not that funny. 

@nikspz any idea what is causing that bug?

**Comment by nikspz** [comment] 2024-05-06 09:38
I cathed this when changed port for gateway. On latest version can't reproduce this one. 

P.s.
Also some commit on development had this issue for `./start` command
![image](https://github.com/hummingbot/hummingbot/assets/83953535/a6425875-7e17-418c-86d5-9d638b60b055)

fix merged to latest development now

**Comment by p-meier** [comment] 2024-05-07 09:53
That sounds great, thanks for the fix. Will see if it works after the next development-branch pull.

**Closed** 2024-07-04 01:46 UTC
Labels: bug

**Comment by gordonkoehn** [comment] 2024-12-15 14:56
I just had the issue again on a pull from `main` today.
