### ISSUE TITLE
Ascendex - doesn't create event when received partially filled orders for low liquidity pairs

### ISSUE THREAD

**Issue by SerK0** [hummingbot/hummingbot#5537] opened 2022-07-26 17:19 UTC
**Describe the bug**
HummingBot doesn't create event when received partially filled orders on Ascendex.

**Steps To Reproduce**
Start pmm strategy for Ascendex BOLT pair.
When buy GTC order placed, sell to it some portion (for example, place 20$ order, sell to it 10$).
There's no any event about buying 10$.

**Release version**
1.6.0

**Attachments**
strategy conf:
[bolt_mm.txt](https://github.com/hummingbot/hummingbot/files/9192041/bolt_mm.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by SerK0** [comment] 2022-08-07 07:28
Is there any updates about this issue?

**Comment by nikspz** [comment] 2023-01-11 11:51
Can't reproduce on latest development 1.12.0, longterm bot recorded all events
should be fixed with latest ascendex connector refactor  https://github.com/hummingbot/hummingbot/pull/5891

**Comment by nikspz** [comment] 2023-01-11 19:49
[fix](https://github.com/hummingbot/hummingbot/pull/5891) has been deployed to development branch and available in the release version 1.11

**Closed by nikspz** 2023-01-11 19:49 UTC
Labels: bug, ascend_ex
