### ISSUE TITLE
Error writing configs: ('cannot represent an object', WindowsPath('C:/dev/hummingbot/logs')

### ISSUE THREAD

**Issue by lt7** [hummingbot/hummingbot#5573] opened 2022-08-07 00:31 UTC
**Describe the bug**
When creating a new strategy on Windows the following error is logged when it attempts to save 
`16812 - root - ERROR - Error writing configs: ('cannot represent an object', WindowsPath('C:/dev/hummingbot/logs'))`

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Open hummingbot, create a new strategy, enter parameters.
2. When saving error will be throw. 
...

**Screenshots**
<img width="1762" alt="image" src="https://user-images.githubusercontent.com/1315232/183270015-6640d6d9-ede3-42d7-8ce2-68c35b403ca8.png">

**Release version**
v1.7.0

**Attachments**
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9275951/logs_hummingbot.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
j0e

**Comment by nikspz** [comment] 2022-08-08 05:51
Hi @lt7, Could you also please add your Hummingbot version, OS, machine type and installation type here?

**Comment by lt7** [comment] 2022-08-08 05:53
> Hi @lt7, Could you also please add your Hummingbot version, OS, machine type and installation type here?

v1.7.0 on Windows 11 (21H2) from source (development branch).

**Comment by nikspz** [comment] 2022-08-17 02:27
Hey @lt7, could you please specify steps to reproduce?
I can't reproduce using WSL and `/mnt/c/test_instance` path (latest development and master branch)
Could you please provide what terminal do you use (the app) and exact commands to reproduce?

**Comment by lt7** [comment] 2022-08-17 03:10
hey @nikspz. I don't use WSL for development. I use PyCharm 2022.1.3 and get the error, or gitbash (https://gitforwindows.org/)

Steps to reproduce
1 - Pull latest development build (c:\dev\hummingbot)
2 - Fix the bitfinex bool issue mentioned in https://github.com/hummingbot/hummingbot/pull/5140 as it still exists in development branch (not a fix but you can change from bool to int so it compiles)

<img width="922" alt="image" src="https://user-images.githubusercontent.com/1315232/185025869-ed529525-efb2-4fcd-93bc-22c1fae5d2bd.png">

3 - ./clean & ./compile
4 - launch, try and create strategy, error occurs.

<img width="1844" alt="image" src="https://user-images.githubusercontent.com/1315232/185025572-6a0ad5cb-751a-424e-82a2-222d37bcfb28.png">

**Comment by nikspz** [comment] 2022-08-17 05:06
@lt7 We discontinued our support for windows gitbash. 
We recommend to run it on WSL to run hummingbot on windows machines.

As Hummingbot is optimized for UNIX-based environments, [install Windows Subsystem for Linux](https://hummingbot.org/installation/docker#install-wsl) in order to deploy an Ubuntu environment in your Windows machine.
https://hummingbot.org/installation/source/#windows

**Comment by lt7** [comment] 2022-08-17 05:45
It doesn't work with PyCharm on windows either, so it's not a gitbash issue per se. 

I run HB on Ubuntu on AWS, but develop on windows and have been using this setup/configuration since v0.38 so this is a newly introduced bug, and easily reproducable and i've provided a PR so it's a bit disappointing if these sort of bugs don't get fixed. 

The documentation https://hummingbot.org/developers/connectors/debug/ doesn't mention anything about WSL either, so some documentation on how to setup WSL configuration for pycharm debugging would be helpful ?

**Comment by nikspz** [comment] 2022-08-17 05:57
@lt7 Currently testing https://github.com/hummingbot/hummingbot/pull/5574
We will have a discussion regarding Pycharm later. Thank you very much for your feedback

**Comment by nikspz** [comment] 2022-09-13 16:48
Fixed with https://github.com/hummingbot/hummingbot/pull/5574

**Closed** 2022-09-13 16:48 UTC
Labels: bug
