### ISSUE TITLE
Crypto.com - Error parsing data on multiple bots using a single API key

### ISSUE THREAD

**Issue by cali-tomas** [hummingbot/hummingbot#3519] opened 2021-06-06 07:55 UTC
**Describe the bug**
Using crypto_com as exchange and using single API key to multiple instance show a prasing error (crypto_com_exchange - Error parsing data)

**Steps to reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Create simple config on PMM and use crypto_com as your exchange
1. Create multiple bots and run, after few seconds/minutes there will be an error
...

```
2021-06-03 13:45:58,061 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-06-03 13:45:58,493 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2021-06-03 13:45:58,861 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_order_book_tracker - INFO - Initialized order book for EGLD-USDT. 1/1 completed.
2021-06-03 13:46:00,180 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - ERROR - Error parsing data from https://api.crypto.com/v2/private/get-account-summary. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 338, in _api_request
    parsed_response = json.loads(await response.text())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Screenshots**
![inline1039161196](https://user-images.githubusercontent.com/85161223/120916932-178c2800-c6df-11eb-87de-7cef32cea36b.png)

**Release version**
v.0.39.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/6604431/logs_conf_pure_mm_1.log)

* log from one of my bot
[logs_mkr.log](https://github.com/CoinAlpha/hummingbot/files/6603814/logs_mkr.log)- log from user
[conf_pure_mm_1.txt](https://github.com/CoinAlpha/hummingbot/files/6606481/conf_pure_mm_1.txt) - config used

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramny4) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment] 2021-06-08 03:46
This was initially reported to the team that it may have been caused by hitting the API rate limit. Looking at the API docs, that issue should throw a `TOO_MANY_REQUESTS` error which is not in the logs.

https://exchange-docs.crypto.com/spot/index.html#rate-limits

@cali-tomas can you run another test - instead of running multiple instances, try creating a bot that creates a total of 10 orders with 30 seconds order refresh time? Send the results here with the information packets.

**Comment by cali-tomas** [comment] 2021-06-08 12:58
This is the result of my testing. The bot works well with 8 order levels (Set to 10 but not enough balance) and 30sec refresh time
![image](https://user-images.githubusercontent.com/85161223/121186139-59f96480-c899-11eb-902a-2846991ae6cd.png)
```
strategy: pure_market_making
exchange: crypto_com
market: EGLD-USDT


bid_spread: 4.0
ask_spread: 5.0
minimum_spread: -100.0
order_refresh_time: 30.0
max_order_age: 1800.0
order_refresh_tolerance_pct: 0.0
order_amount: 0.13


price_ceiling: -1.0
price_floor: -1.0

ping_pong_enabled: false

inventory_skew_enabled: false
inventory_target_base_pct: 50.0
inventory_range_multiplier: 1.0
inventory_price: 1.0

order_levels: 10
order_level_amount: 0.001
order_level_spread: 0.001


filled_order_delay: 60.0

hanging_orders_enabled: false
hanging_orders_cancel_pct: 10.0

order_optimization_enabled: false
ask_order_optimization_depth: 0.0
bid_order_optimization_depth: 0.0

add_transaction_costs: false

price_source: current_market
price_type: mid_price
price_source_exchange:
price_source_market:
price_source_custom_api:
take_if_crossed:
order_override:
```
```
2021-06-08 12:47:38,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (EGLD-USDT) Creating 9 bid orders at (Size, Price): ['0.13 EGLD, 83.5546 USDT', '0.131 EGLD, 83.5537 USDT', '0.132 EGLD, 83.5529 USDT', '0.133 EGLD, 83.552 USDT', '0.134 EGLD, 83.5511 USDT', '0.135 EGLD, 83.5503 USDT', '0.136 EGLD, 83.5494 USDT', '0.137 EGLD, 83.5485 USDT', '0.001 EGLD, 83.5476 USDT']
2021-06-08 12:47:38,126 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001707 for 0.131 EGLD-USDT.
2021-06-08 12:47:38,126 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.131", "price": "83.5537", "order_id": "HBOT-B-EGLD-USDT-1623156458001707", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,136 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001809 for 0.136 EGLD-USDT.
2021-06-08 12:47:38,136 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.136", "price": "83.5494", "order_id": "HBOT-B-EGLD-USDT-1623156458001809", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,144 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001791 for 0.135 EGLD-USDT.
2021-06-08 12:47:38,144 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.135", "price": "83.5503", "order_id": "HBOT-B-EGLD-USDT-1623156458001791", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,152 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001753 for 0.133 EGLD-USDT.
2021-06-08 12:47:38,152 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.133", "price": "83.5520", "order_id": "HBOT-B-EGLD-USDT-1623156458001753", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,160 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001774 for 0.134 EGLD-USDT.
2021-06-08 12:47:38,160 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.134", "price": "83.5511", "order_id": "HBOT-B-EGLD-USDT-1623156458001774", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,200 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001732 for 0.132 EGLD-USDT.
2021-06-08 12:47:38,201 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.132", "price": "83.5529", "order_id": "HBOT-B-EGLD-USDT-1623156458001732", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,210 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001824 for 0.137 EGLD-USDT.
2021-06-08 12:47:38,210 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.137", "price": "83.5485", "order_id": "HBOT-B-EGLD-USDT-1623156458001824", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,250 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001644 for 0.130 EGLD-USDT.
2021-06-08 12:47:38,252 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.130", "price": "83.5546", "order_id": "HBOT-B-EGLD-USDT-1623156458001644", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}
2021-06-08 12:47:38,263 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Created LIMIT_MAKER BUY order HBOT-B-EGLD-USDT-1623156458001840 for 0.001 EGLD-USDT.
2021-06-08 12:47:38,263 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1623156458.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "EGLD-USDT", "amount": "0.001", "price": "83.5476", "order_id": "HBOT-B-EGLD-USDT-1623156458001840", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "crypto_com"}```

**Comment by 7Mik** [comment] 2021-08-13 09:55
Using one single api key every three instances solved the issue for me.
Your mileage may vary if you have more order levels or higher or lower refresh time

**Comment by rapcmia** [comment] 2022-02-25 04:54
Tested on the current version using PMM same API and markets getting the same behavior

```
2022-02-25 04:34:00,129 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - ERROR - Error parsing data from https://api.crypto.com/v2/private/get-account-summary. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 343, in _api_request
    parsed_response = json.loads(await response.text())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 558, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 579, in _update_balances
    account_info = await self._api_request("post", CONSTANTS.GET_ACCOUNT_SUMMARY_PATH_URL, {}, True)
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 345, in _api_request
    raise IOError(f"Error parsing data from {url}. Error: {str(e)}")
```

This happens when you create multiple bots with same API, markets with only 1 set of order at the same time. When I tested it by just using two bots w/ multiple orders [6 and 10] instead of multiple bots w/ single order, it seems to work just fine.

**Comment by rapcmia** [comment] 2022-04-28 08:55
Closing ticket, workaround for this issue is to setup a config with multiple order levels rather using multiple testbots for same market on a single order

**Closed by rapcmia** 2022-04-28 08:55 UTC
Labels: P3, bug, crypto_com
