### ISSUE TITLE
Client - UserWarning "Trying to detect encoding from a tiny portion of (16) byte(s)" when getting filled orders

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6559] opened 2023-08-31 15:23 UTC
### Describe the bug

Everytime getting an order filled when testing a pull request or running connector checks, we are getting this UserWarning on log panel:

![image](https://github.com/hummingbot/hummingbot/assets/73840223/267a9654-4c96-4774-b22c-dd18e8558717)

```
/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/charset_normalizer/api.py:105: UserWarning: Trying to detect encoding from a tiny portion of (16) byte(s).
warn('Trying to detect encoding from a tiny portion of ({}) byte(s).'.format(length))
```

Error does not show on log file and does not affect client performance nor crashed. Ticket created for monitoring purpose tto look for possible effect on long term bots 

### Steps to reproduce

1. Setup any script or strategy supported by Hummingbot
2. Wait for your orders to get filled 
3. Observe log panel

### Release version

dev-1.20.0

### Type of installation

Source

### Attach required files

None

**Comment by nikspz** [comment] 2023-09-07 05:50
Adding bounty for this issue:

Severity: P2
Bounty: 50,000 HBOT
Rationale: An investigation task and a possible fix for this issue related to packages when an order filled event happened

**Comment by nikspz** [comment] 2023-09-08 05:01
Closing this bounty and issue.  Can't reproduce on fresh installation (deleted all conda env and did the fresh Client install)

**Comment by rapcmia** [comment] 2023-09-19 12:38
Github issue reopened, issue reocurred when testing https://github.com/hummingbot/hummingbot/pull/6520#

Steps to reproduce:
1. When an order gets filled, observe log panel for the error.
2. No logs available

![image](https://github.com/hummingbot/hummingbot/assets/73840223/f19b5916-f521-47a0-8a40-dcfc4bac3f30)

**Comment by bilalmotiwala** [comment] 2023-09-20 07:00
Hey folks, new here but just to add into the observations above. The error caused on the order fulfilled event stops future orders from being made.

So if I run an order_level of 2 and then face this on let's say a BUY order, the next refresh will generate 1 BUY and 2 SELLS and as the error continues to show up, the number of order per refresh continue to drop.

Using via the Docker Install method on MacOS Ventura and M2 chipset.

**Comment by nikspz** [comment] 2023-09-29 13:58
Opened this bounty again

**Comment by isreallee82** [comment] 2023-10-02 15:03
@rapcmia you might need to update your condo  environment cause I can't reproduce the error and I see the error have to do with encoding, so my guess is the charset_normaliser is outdated

chardet seems to be unmantained. Check https://pypi.org/project/charset-normalizer @bilalmotiwala 



![Image](https://github.com/hummingbot/hummingbot/assets/70828114/c20de1da-ab50-42ab-a15a-fb18d9311045)


![Image](https://github.com/hummingbot/hummingbot/assets/70828114/3b57f861-b4bc-4a07-bca4-2154567f9fcc)

**Comment by tomasgaudino** [comment] 2023-11-07 16:43
Hi guys, I just tried to reproduce this error with dev-1.22.0 and I couldn't

1) Initial setup
	a) git clone --branch development https://github.com/hummingbot/hummingbot
	b) ./install
	c) conda activate hummingbot
	d) ./compile
	e) Connect binance
	f) Create pmm strategy -> conf_pure_mm_2.yml
		- strategy: pure_market_making
		- market spot connector: binance
		- trading pair: ETH-USDT
		- first bid: 0.01
		- first ask: 0.01
		- order refresh time: 120s
		- amount eth: 0.001
		- ping pong: no

2) Start script
	a) import conf_pure_mm_2
	b) start
	



![Image](https://github.com/hummingbot/hummingbot/assets/69804854/e91ee310-a17b-4ed7-8282-eaa9c460f8d0)

**Comment by nikspz** [comment] 2023-11-08 04:21
Reviewed 1.21.0 regression tests logs, Closing this issue as couldn't reproduce on latest

**Closed by nikspz** 2023-11-08 04:21 UTC
Labels: P2, bug
