### ISSUE TITLE
AMM Arbitrage strategy stuck on "waiting for allowances" on Polygon

### ISSUE THREAD

**Issue by FlorentG74** [hummingbot/hummingbot#5915] opened 2022-11-28 21:25 UTC
**Describe the bug**
I'm facing the 'waiting for allowances' issue when trying to run the amm_arb strategy (config attached) on both Uniswap and Quickswap on the Polygon network.
I can see my balances from hummingbot & have approved the tokens on the uniswap app (swapped tokens back and forth on their app).
I checked the token list as well after seeing the issue open on github & the tokenlist does include both MATIC and USDT by default (allTokens.tokenlist.json) 

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Connect to binance & uniswap/quickswap exchange on the polygon network
2. Start the bot
3. The bot will loop on 'waiting for allowances' and never start trading

**Screenshots**
![image](https://user-images.githubusercontent.com/84814284/204383114-4dc94559-11ee-4bb8-826d-c14c61f36ef8.png)

**Release version**
1.9.0/1.10.0

**Attachments**

[conf_MATIC-USDT_amm_arb_1.zip](https://github.com/hummingbot/hummingbot/files/10107594/conf_MATIC-USDT_amm_arb_1.zip)

Discord: FlorentG74

**Comment by jellyjamin** [comment] 2022-11-29 22:39
It also does that for avalanche on open ocean for version 1.1

**Comment by rapcmia** [comment] 2022-11-30 05:59
Hi @FlorentG74 good day
Thanks for submitting this ticket, I can confirm that I am experiencing this issue when using WMATIC and MATIC. I ran some tests observed this even when I tried to setup a modified tokenlist. We will consult our dev team for advice how we can proceed with a fix or a workaround and get back to you. Thank you 🙇

**Comment by rapcmia** [comment] 2022-11-30 06:01
Hi @jellyjamin we appreciate your comment however it would be best if you can open a ticket related to avalanche instead. Atm I am able to run some markets working as expected.  Please create a [separate ticket](https://github.com/hummingbot/hummingbot/issues/new/choose) and add the details needed thank you

**Comment by FlorentG74** [comment] 2022-11-30 07:33
Thanks @rapcmia; please let me know if anything else's needed from my end.

**Comment by FlorentG74** [comment] 2022-12-03 18:37
Hi @rapcmia , I've debugged the issue & have found the root cause; Allowances check fails on the chain's native token (MATIC in my case) when not on Ethereum. I've put a fix together and will propose a pull request if there's interest from the community (currently testing).

**Comment by rapcmia** [comment] 2022-12-05 08:19
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Related to gateway specifically on polygon uniswap/quickswap connector stuck on waiting for allowance.

**Comment by rapcmia** [comment] 2022-12-05 08:22
Hi @FlorentG74 thanks for your update, I think its better to add a bounty for this issue for a community fix since our dev team is still working for the improvements of gateway. You may want to assigned this to you and submit your pull request ✌️

**Comment by FlorentG74** [comment] 2022-12-05 09:42
@rapcmia sure let's do this.

**Comment by JeremyKono** [comment] 2022-12-07 03:17
Assigning this issue to @FlorentG74

**Comment by rapcmia** [comment] 2022-12-12 07:33
Hi @FlorentG74 good day,
Just want to follow for a possible update for the PR? Thank you!

**Comment by asggWa** [comment] 2022-12-13 17:57
i am having same issue and trying solve adding some eth balanc to account for gass matter. not sure solve the isue issue. if i solve doing this i will tell you.

**Comment by alg0mas** [comment] 2022-12-17 20:26
> Hi @rapcmia , I've debugged the issue & have found the root cause; Allowances check fails on the chain's native token (MATIC in my case) when not on Ethereum. I've put a fix together and will propose a pull request if there's interest from the community (currently testing).

@FlorentG74 How did testing go?

**Comment by FlorentG74** [comment] 2022-12-18 17:45
hi, The fix on 'waiting for allowances' is ready - will create the PR tonight. I'm still struggling to get consistent quotes on uniswap/MATIC though so there might be other tweaks to perform in the setup, will keep looking

**Comment by alg0mas** [comment] 2022-12-18 18:12
> hi, The fix on 'waiting for allowances' is ready - will create the PR tonight. I'm still struggling to get consistent quotes on uniswap/MATIC though so there might be other tweaks to perform in the setup, will keep looking

Thanks for the update. Not sure it will help with the quotes, but have you tried adding the missing WMATIC token? 

`    {
      "address": "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270",
      "decimals": 18,
      "symbol": "WMATIC",
      "name": "WMATIC"
    },` can be added to `src/chains/polygon/polygon_tokens_mainnet.json` then update `tokenListSource` in `gateway/src/templates/polygon.yml`

**Comment by wackytrader** [comment] 2023-01-07 14:58
this is happening as well on amm_arb for sushiswap/uniswap on SNX-ETH pair 
![image](https://user-images.githubusercontent.com/108702725/211157015-8201d4e0-2eb9-41a1-9407-d65245dc4a40.png)

**Comment by nikspz** [comment] 2023-01-09 21:29
@wackytrader 
the reason could be SNX is not available in default tokenlist (.../gateway/src/chains/ethereum/erc20_tokens_goerli.json)
p.s. Also bot showed SNX-ETH is not active pair on uniswap_ethereum_goerli

**Comment by shalee83** [comment] 2023-01-11 18:19
Any news on this? I'm getting the same error for AMM ARB Uniswap Ethereum Goerli with an ETH-WETH pair (doesn't make sense I know, just because I have both test coins and there is not much more in the pool?)

**Comment by rapcmia** [comment] 2023-01-12 12:52
Hi @shalee83, @wackytrader good day
Please be advised that this ticket was intended for Polygon and not for Ethereum Goerli. You may want to open a ticket for the issue and add the required info for us to investigate.

**Comment by rapcmia** [comment] 2023-01-12 13:17
Hi @FlorentG74 
We are able to setup WMATIC-USDT on Quickswap using the latest update on Gateway. Users would now need to manually approve the tokens on the connector before they can use it on gateway, see screenshot of the test we did for MATIC-USDT

Approve USDT 
![image](https://user-images.githubusercontent.com/73840223/212075317-a190f09f-b1b2-41b6-bac0-82c764af0c6f.png)

Setup quickswap WMATIC-USDT, triggered `markets are ready` and `no arbitrage opportunity`
![image](https://user-images.githubusercontent.com/73840223/212075571-875b16e6-1b46-43c0-9f11-15566b2fe517.png)

You may want to check our development branch. The update will be available next Hummingbot version 1.12.0.

**Comment by FlorentG74** [comment] 2023-01-12 13:19
Perfect thanks for the good news. Will update to latest dev and verify.

Thanks

**Comment by nikspz** [comment] 2023-01-12 14:58
Closing this issue, can't reproduce using latest dev branch. (dev-1.12.0)
Bot's able to do the trades on uniswap_polygon_mainnet and kucoin then when it out of funds and displayed no arb opportunity.

Before the start in some cases you need to manually approve tokens on the exchange side as described above.

[issue5915.zip](https://github.com/hummingbot/hummingbot/files/10402878/issue5915.zip)

![image](https://user-images.githubusercontent.com/83953535/212097579-e49ca520-793f-45b2-931a-fda2ba869328.png)
https://polygonscan.com/tx/0xf9eec39d512b645c198fd8d6251017c95223f2ffa1367a569b225dc69023d410
https://polygonscan.com/tx/0xa2813b3b0f1a1cb6637cf5db441944f63b18d19b5539e01c156818eb7d476da7

**Closed by nikspz** 2023-01-12 14:58 UTC
Labels: P3, bug, gateway, polygon

**Comment by shalee83** [comment] 2023-01-13 11:24
> Hi @shalee83, @wackytrader good day Please be advised that this ticket was intended for Polygon and not for Ethereum Goerli. You may want to open a ticket for the issue and add the required info for us to investigate.

Sure, alright, thanks

**Comment by shalee83** [comment] 2023-01-13 16:25
> @wackytrader the reason could be `SNX` is not available in default tokenlist (need to be added here: `.../gateway/src/chains/ethereum/erc20_tokens_goerli.json`) p.s. Also bot showed SNX-ETH is not active pair on uniswap_ethereum_goerli

Turns out this was the solution for me - thanks!

**Comment by fengtality** [comment] 2023-05-09 17:34
@FlorentG74 Hummingbot foundation is unassigning you from this bounty since issue is resolved.
