### ISSUE TITLE
Exchange base order_book_ask_entries / bid method returns incorrect orderbook prices

### ISSUE THREAD

**Issue by leocape** [hummingbot/hummingbot#6021] opened 2023-01-20 12:02 UTC
**Describe the bug**
// A clear and concise description of what the bug is.

The helper methods `order_book_bid_entries` and `order_book_ask_entries` in `exchange_base.pyx `return incorrect prices for the orders in the order book, for example price 17.77 with order_quantum 0.01 returns 17.76.

Context:
These methods return an iterator of the local orderbook, with the `ClientOrderBookRow` class being the iterator type of which it's price and amount type is `Decimal`.

For performance, the local orderbook is a class of `OrderBookRows` which keep their prices in `float` (faster than `Decimal`), so these prices need to be converted into `Decimal` to suit the return type of `ClientOrderBookRow` in the methods above.

The methods above however when converting from `float` to `Decimal` do not convert the float to `String` first, but are converting directly to `Decimal`, which is causing rounding issues. Further to that, as these prices and amounts are already quantized (they come directly from the connector / exchange), they do not need to be quantized again at this point.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Difficult to reproduce without providing an entire strategy and as the rounding error only happens on certain numbers , but can be seen inside a strategy while using a non liquid pair (so that the orderbook is not moving quickly) whose price quantum is 0.01, when calling the method:

```
for order in self._exchange.order_book_ask_entries(self._trading_pair):
            top_ask_price = order.price
```

This top ask price is incorrect, in my testing the exchange order was 17.77, and the top_price here was 17.76.

**Screenshots**
// If applicable, add screenshots to help explain your problem.
na
**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
1.11.0 (was present in previous versions too since the diff mentioned above)
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
na

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
leocape

discord chat:
Last message in conversation:
https://discord.com/channels/530578568154054663/557343500908363786/1067876648915050627

**Comment by leocape** [comment] 2023-01-25 14:47
![image](https://user-images.githubusercontent.com/67806134/214594172-1b31150c-4b9e-4417-97fa-80ee1a62fc6f.png)

**Comment by MementoRC** [comment] 2023-01-25 21:06
@leocape Based on our discussion, this is not the right illustration of the overall issue you have, correct?

**Comment by leocape** [comment] 2023-01-26 06:00
@MementoRC Correct - I have updated it and the issue description and title as well thanks

**Comment by nikspz** [comment] 2023-03-10 06:26
This issue is assigned to HB Foundation team

**Comment by nikspz** [comment] 2023-05-12 13:45
Closing the issue since no response from the user on how to reproduce

**Closed by nikspz** 2023-05-12 13:45 UTC
Labels: bug
