### ISSUE TITLE
dYdX perpetual - Orders failed event causing active orders not recognized and stuck on exchange

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6716] opened 2023-12-14 14:41 UTC
### Describe the bug

When testing v2 strategy on dYdX perpetual, observed that it ended up`Not enough budget to open position.` when initially it started with multi level orders and no filled event happened. Decided to run again a long term bot using v1 strategy (Perpetual Market making) and left it for couple of hours (9hrs).

Observed that the connector now is stuck on `Insufficient balance...You are also at a possible risk of being liquidated if there happens to be an open loss.` which is expected if you dont have enough balance to post orders on exchange.

![image](https://github.com/hummingbot/hummingbot/assets/73840223/ca4e9c0e-8051-42e1-b206-771ebc07225b)
- Noticed that the available balance is at negative
- While this happened, there are orders that are stuck on exchange. Even `stop` command does not recognized these orders
   ![image](https://github.com/hummingbot/hummingbot/assets/73840223/2ad23762-fb4c-4030-a419-531efc332230)
     - Review log file and found out upon creating orders, got a order failed event resulting to connector not recognize it and left on exchange as active
        - 2023-12-14 13:22:02,002 Created buy orders
            - Creating buy order 14.470 HummingbotBLKUD60c7176aabdffed184d098c22
            - Creating buy order 14.617 HummingbotBLKUD60c7176aabdc7ed184d098c22
        - 2023-12-14 13:22:02,778 Order update failed for HummingbotBLKUD60c7176aabdffed184d098c22
        - 2023-12-14 13:22:02,775 Order update failed for HummingbotBLKUD60c7176aabdc7ed184d098c22
        - 2023-12-14 13:23:02,004 Reached set order refresh time (60s) but these orders are not canceled
          ```
          2023-12-14 13:22:02,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Creating 2 LIMIT bid orders at (Size, Price): ['1.6 LINK, 14.617 USD', '1.6 LINK, 14.47 USD'] to OPEN position.
          2023-12-14 13:22:02,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Creating 2  LIMIT ask orders at (Size, Price): ['1.6 LINK, 14.913 USD', '1.6 LINK, 15.06 USD'] to OPEN position.
          2023-12-14 13:22:02,423 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HummingbotSLKUD60c7176aabe6fed184d098c22 for 1.6 to OPEN a LINK-USD position.
          2023-12-14 13:22:02,423 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "14.913", "order_id": "HummingbotSLKUD60c7176aabe6fed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": "1f73be6e95dfc2db0699e088ba08b4c0b679bfae214dc86a30dc9df3fff2acb", "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
          2023-12-14 13:22:02,427 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HummingbotSLKUD60c7176aabe8aed184d098c22 for 1.6 to OPEN a LINK-USD position.
          2023-12-14 13:22:02,427 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "15.060", "order_id": "HummingbotSLKUD60c7176aabe8aed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": null, "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
          2023-12-14 13:22:02,595 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HummingbotBLKUD60c7176aabdc7ed184d098c22 for 1.6 to OPEN a LINK-USD position.
          2023-12-14 13:22:02,596 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "14.617", "order_id": "HummingbotBLKUD60c7176aabdc7ed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": null, "leverage": 10, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "dydx_perpetual"}
          2023-12-14 13:22:02,626 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HummingbotBLKUD60c7176aabdffed184d098c22 for 1.6 to OPEN a LINK-USD position.
          2023-12-14 13:22:02,626 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "14.470", "order_id": "HummingbotBLKUD60c7176aabdffed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": null, "leverage": 10, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "dydx_perpetual"}
          2023-12-14 13:22:02,771 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "order_id": "HummingbotBLKUD60c7176aabdc7ed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
          2023-12-14 13:22:02,775 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotBLKUD60c7176aabdc7ed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702531322.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotBLKUD60c7176aabdc7ed184d098c22', exchange_order_id=None, misc_updates=None)
          2023-12-14 13:22:02,775 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "order_id": "HummingbotBLKUD60c7176aabdffed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
          2023-12-14 13:22:02,778 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotBLKUD60c7176aabdffed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702531322.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotBLKUD60c7176aabdffed184d098c22', exchange_order_id=None, misc_updates=None)
          ```
        - 2023-12-14 15:14:21,025 Creating 2 buy and sell orders
          - All orders got order failed, 3/4 of orders stuck on exchange
          - Sell order for `14.943` had same failed order but no active order on exchange
          ```
          2023-12-14 15:14:21,025 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Creating 2 LIMIT bid orders at (Size, Price): ['1.6 LINK, 14.647 USD', '1.6 LINK, 14.499 USD'] to OPEN position.
          2023-12-14 15:14:21,026 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Creating 2  LIMIT ask orders at (Size, Price): ['1.6 LINK, 14.943 USD', '1.6 LINK, 15.091 USD'] to OPEN position.
          2023-12-14 15:14:21,347 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702538061.0, "order_id": "HummingbotBLKUD60c7308581364ed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
          2023-12-14 15:14:21,350 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotBLKUD60c7308581364ed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702538061.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotBLKUD60c7308581364ed184d098c22', exchange_order_id=None, misc_updates=None)
          2023-12-14 15:14:21,350 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702538061.0, "order_id": "HummingbotBLKUD60c73085813a6ed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
          2023-12-14 15:14:21,351 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotBLKUD60c73085813a6ed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702538061.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotBLKUD60c73085813a6ed184d098c22', exchange_order_id=None, misc_updates=None)
          2023-12-14 15:14:21,351 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702538061.0, "order_id": "HummingbotSLKUD60c7308581424ed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
          2023-12-14 15:14:21,352 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotSLKUD60c7308581424ed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702538061.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotSLKUD60c7308581424ed184d098c22', exchange_order_id=None, misc_updates=None)
          2023-12-14 15:14:21,353 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702538061.0, "order_id": "HummingbotSLKUD60c7308581443ed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
          2023-12-14 15:14:21,354 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotSLKUD60c7308581443ed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702538061.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotSLKUD60c7308581443ed184d098c22', exchange_order_id=None, misc_updates=None)
          2023-12-14 15:15:21,001 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Insufficient balance: BUY order (price: 14.659, size: 1.6) is omitted.
          2023-12-14 15:15:21,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - You are also at a possible risk of being liquidated if there happens to be an open loss.
          2023-12-14 15:15:21,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Insufficient balance: BUY order (price: 14.511, size: 1.6) is omitted.
          2023-12-14 15:15:21,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - You are also at a possible risk of being liquidated if there happens to be an open loss.
          2023-12-14 15:15:21,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Insufficient balance: SELL order (price: 14.955, size: 1.6) is omitted.
          2023-12-14 15:15:21,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - You are also at a possible risk of being liquidated if there happens to be an open loss.
          2023-12-14 15:15:21,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Insufficient balance: SELL order (price: 15.103, size: 1.6) is omitted.
          2023-12-14 15:15:21,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - You are also at a possible risk of being liquidated if there happens to be an open loss.
          2023-12-14 15:15:22,006 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Insufficient balance: BUY order (price: 14.659, size: 1.6) is omitted.
          2023-12-14 15:15:22,007 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - WARNING - You are also at a possible risk of being liquidated if there happens to be an open loss.
          2023-12-14 15:15:22,007 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Insufficient balance: BUY order (price: 14.511, size: 1.6) is omitted.
          ```

### Steps to reproduce

1. Setup dYdX connector on either V2 strategy or Perpetual market making 
2. Run for couple of hours then check the status or logs of the client 

### Release version

dev-1.23.0

### Type of installation

Source

### Attach required files

[logs_perp-test1.log](https://github.com/hummingbot/hummingbot/files/13674637/logs_perp-test1.log)
[logs_test-dydx1.log](https://github.com/hummingbot/hummingbot/files/13674640/logs_test-dydx1.log)
[perp-test1.yml.log](https://github.com/hummingbot/hummingbot/files/13674644/perp-test1.yml.log) `remove .log`

**Comment by tijsk** [comment] 2024-01-27 11:56
I'm having the same issue. Stopping the bot and starting it again makes it work again. Issue occurs every few hours.

**Comment by nikspz** [comment] 2024-01-30 07:03
Bounty: dYdX perpetual - Orders failed event causing active orders not recognized and stuck on exchange

Description:
There is a bug observed in the dYdX Perpetual Market Making strategy where orders failed events are not handled properly. This leads to active orders not being recognized by the connector and getting stuck on the exchange, causing potential issues like insufficient balance and being at risk of liquidation.

Expected Outcome:
Orders failed events should be handled appropriately, and the connector should recognize and manage active orders accordingly. Stuck orders on the exchange should be avoided.

Deliverables:
1. Identify the root cause of the issue related to orders failed events.
2. Implement a fix to handle orders failed events properly.
3. Ensure that active orders are recognized and managed correctly by the connector.

Submission Guidelines:
https://hummingbot.org/developers/contributions/
Provide a pull request with the fix to development branch of the Hummingbot repository. Include a detailed explanation of the changes made, and confirm that the issue is resolved through testing.

**Bounty**
- Sponsor: Hummingbot Foundation
- Bounty amount: 50K HBOT
- Developer portion: 50K HBOT

**Comment by harjas27** [comment] 2024-02-22 19:42
I would like to work on this one, suspect this as the cause:

`OrderTracker` maintains two dicts - `_tracked_limit_orders` and `_shadow_tracked_limit_orders`. Whenever a limit order
is created, it gets added two both of these.
When the order is failed, `StrategyBase::c_did_fail_order_tracker()` calls `c_stop_tracking_limit_order` and this removes
the order from `_tracked_limit_orders`.
Now after 1 minute, when cancel is called in the strategy, only the active orders are cancelled on exchange.
For the first case pointed out in the issue, 2 buys and 2 sells got created. When the 2 buys failed, they got removed
from the active orders list and thus were never cancelled - got stuck on exchange

**Comment by nikspz** [comment] 2024-02-22 19:49
@harjas27 Do you want to be assigned for this Bounty ticket?

**Comment by harjas27** [comment] 2024-02-23 08:19
yes

**Comment by nikspz** [comment] 2024-02-23 12:46
Assigned to @harjas27  , please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by harjas27** [comment] 2024-03-01 20:04
Added the fix, can you review? @nikspz

**Comment by nikspz** [comment] 2024-03-14 04:12
Unassigned developer since fix changing perpetualMM strategy files, (the fix should be done to dYdX connector files)

**Comment by nikspz** [comment] 2024-03-14 04:13
Closing /remove bounty for this issue, will recheck after https://github.com/hummingbot/hummingbot/issues/6897 done

**Closed** 2024-10-31 14:51 UTC
Labels: P2, bug, dydx_perpetual
