### ISSUE TITLE
Dex orders are failing on polygon

### ISSUE THREAD

**Issue by berikarg** [hummingbot/hummingbot#5866] opened 2022-11-05 15:13 UTC
**Describe the bug**
// A clear and concise description of what the bug is.
During amm_arb strategy all orders on polygon dexes (Quickswap and Uniswap) are failing. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

I am running amm_arb between quickswap WBTC-USDC and kucoin BTC-USDC. 14 arbitrage opportunities were found. All orders on kucoin have been successfully executed. All orders on quickswap have failed. On polygonscan I can see only 3 transactions, all failed with UniswapV2Router: EXPIRED error. 

Later changed Quickswap to Uniswap and gateway_transaction_cancel_interval to 600. Found 3 arb opportunities. None of uniswap orders did succeed. Only 1 transaction visible on polygonscan: failed with "Transaction too old" error.

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/81421552/200126230-4ebfaecb-a523-4c6e-b608-11434b98c12c.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
1.9.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[bug-report.zip](https://github.com/hummingbot/hummingbot/files/9944103/bug-report.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
blockchain-learner#8585

I assume the problem is that the gas price was too low. It would be convenient to be able to manipulate it via config somehow.

**Comment by rapcmia** [comment] 2022-11-29 06:32
Hi @berikarg good day to you and thanks for submitting this ticket.
I tried to reproduce this issue and monitor the results, I can confirm that some of my orders are filled but there are also failed tx with [error](https://polygonscan.com/tx/0x4947327161781d4b540716067bd44b40da40710400a9e21b8a94e69b58af6262) of `Fail with error 'TransferHelper: TRANSFER_FROM_FAILED'` and I'm not able to reproduce this `"Transaction too old"`

```
# Fail with error 'TransferHelper: TRANSFER_FROM_FAILED'
2022-11-29 13:56:59,994 - 4185 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order buy-WBTC-USDC-1669701416281450 for 0.000700 WBTC-USDC.
2022-11-29 13:57:00,010 - 4185 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1669701419.0, "type": "OrderType.LIMIT", "trading_pair": "WBTC-USDC", "amount": "0.000700", "price": "16701.686230000000000", "order_id": "buy-WBTC-USDC-1669701416281450", "creation_timestamp": 1669701416.0, "exchange_order_id": "0xacada9ab0cc5e52338c32c0aed6f60eb1a599b1e069175d40fb7b8e53478be9d", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "quickswap_polygon_mainnet"}
2022-11-29 13:57:08,668 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:10,605 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:12,688 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:15,340 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:17,658 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:20,303 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:22,684 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:24,703 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:26,961 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:28,626 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:30,571 - 4185 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WBTC-USDC-1669701416281450.
2022-11-29 13:57:30,585 - 4185 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1669701450.0, "order_id": "buy-WBTC-USDC-1669701416281450", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "quickswap_polygon_mainnet"}
2022-11-29 13:57:30,586 - 4185 - hummingbot.connector.client_order_tracker - INFO - Order buy-WBTC-USDC-1669701416281450 has failed. Order Update: OrderUpdate(trading_pair='WBTC-USDC', update_timestamp=1669701450.0, new_state=<OrderState.FAILED: 6>, client_order_id='buy-WBTC-USDC-1669701416281450', exchange_order_id=None, misc_updates=None)
```

While this happens I noticed both of our logs have same return failed order 
```
2022-11-03 14:16:38,432 - 1 - hummingbot.connector.client_order_tracker - INFO - Order buy-WBTC-USDC-1667484946044583 has failed. Order Update: OrderUpdate(trading_pair='WBTC-USDC', update_timestamp=1667484998.0, new_state=<OrderState.FAILED: 6>, client_order_id='buy-WBTC-USDC-1667484946044583', exchange_order_id=None, misc_updates=None)
```

We will have to check this with our dev team as well for advice and possible fix, else we can open a bounty for community for a fix. Thank you

[logs_amm-quickswap.log-1.txt](https://github.com/hummingbot/hummingbot/files/10110347/logs_amm-quickswap.log-1.txt)

**Comment by nikspz** [comment] 2023-01-12 17:46
Closing this issue as Resolved, can't reproduce using latest dev branch. (dev-1.12.0)
Bot's able to do the trades on quickswap_polygon_mainnet and kucoin.

Before the start in some cases you need to manually approve tokens on the exchange side as described [here](https://github.com/hummingbot/hummingbot/issues/5915#issuecomment-1380340509)

[issue5886.zip](https://github.com/hummingbot/hummingbot/files/10404410/issue5886.zip)

![image](https://user-images.githubusercontent.com/83953535/212138862-7702a8e8-90ef-4f6c-a18a-987a394c30ec.png)
https://polygonscan.com/tx/0x5d03635ec5df2bbb54c1a59005c720295f2830621fe7e7818f54b55b696d7593
https://polygonscan.com/tx/0xdfbdfa5f8c0b71ab4bb8069a8b3fd70d6310b7a97294b0c8024e2e21a9dd3f73

**Closed by nikspz** 2023-01-12 17:46 UTC
Labels: P3, bug, gateway, polygon
